# generated by datamodel-codegen:
#   filename:  LPA_var_info.json
#   timestamp: 2024-05-02T12:23:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Query(BaseModel):
    genome_release: str
    chromosome: str
    pos: int
    reference: str
    alternative: str


class Cadd(BaseModel):
    Chrom: str
    Pos: int
    Ref: str
    Alt: str
    Type: str
    Length: int
    AnnoType: str
    Consequence: str
    ConsScore: int
    ConsDetail: str
    GC: float
    CpG: float
    motifECount: None
    motifEName: None
    motifEHIPos: None
    motifEScoreChng: None
    oAA: str
    nAA: str
    GeneID: str
    FeatureID: str
    GeneName: str
    CCDS: str
    Intron: None
    Exon: str
    cDNApos: int
    relcDNApos: float
    CDSpos: int
    relCDSpos: float
    protPos: int
    relProtPos: float
    Domain: str
    Dst2Splice: None
    Dst2SplType: None
    minDistTSS: int
    minDistTSE: int
    SIFTcat: str
    SIFTval: float
    PolyPhenCat: str
    PolyPhenVal: float
    priPhCons: float
    mamPhCons: float
    verPhCons: float
    priPhyloP: float
    mamPhyloP: float
    verPhyloP: float
    bStatistic: int
    targetScan: None
    mirSVR_Score: None = Field(..., alias='mirSVR-Score')
    mirSVR_E: None = Field(..., alias='mirSVR-E')
    mirSVR_Aln: None = Field(..., alias='mirSVR-Aln')
    cHmm_E1: int
    cHmm_E2: int
    cHmm_E3: int
    cHmm_E4: int
    cHmm_E5: int
    cHmm_E6: int
    cHmm_E7: int
    cHmm_E8: int
    cHmm_E9: int
    cHmm_E10: int
    cHmm_E11: int
    cHmm_E12: int
    cHmm_E13: int
    cHmm_E14: int
    cHmm_E15: int
    cHmm_E16: int
    cHmm_E17: int
    cHmm_E18: int
    cHmm_E19: int
    cHmm_E20: int
    cHmm_E21: int
    cHmm_E22: int
    cHmm_E23: int
    cHmm_E24: int
    cHmm_E25: int
    GerpRS: float
    GerpRSpval: float
    GerpN: float
    GerpS: float
    tOverlapMotifs: None
    motifDist: None
    EncodeH3K4me1_sum: float = Field(..., alias='EncodeH3K4me1-sum')
    EncodeH3K4me1_max: float = Field(..., alias='EncodeH3K4me1-max')
    EncodeH3K4me2_sum: float = Field(..., alias='EncodeH3K4me2-sum')
    EncodeH3K4me2_max: float = Field(..., alias='EncodeH3K4me2-max')
    EncodeH3K4me3_sum: float = Field(..., alias='EncodeH3K4me3-sum')
    EncodeH3K4me3_max: float = Field(..., alias='EncodeH3K4me3-max')
    EncodeH3K9ac_sum: float = Field(..., alias='EncodeH3K9ac-sum')
    EncodeH3K9ac_max: float = Field(..., alias='EncodeH3K9ac-max')
    EncodeH3K9me3_sum: float = Field(..., alias='EncodeH3K9me3-sum')
    EncodeH3K9me3_max: float = Field(..., alias='EncodeH3K9me3-max')
    EncodeH3K27ac_sum: float = Field(..., alias='EncodeH3K27ac-sum')
    EncodeH3K27ac_max: float = Field(..., alias='EncodeH3K27ac-max')
    EncodeH3K27me3_sum: float = Field(..., alias='EncodeH3K27me3-sum')
    EncodeH3K27me3_max: float = Field(..., alias='EncodeH3K27me3-max')
    EncodeH3K36me3_sum: float = Field(..., alias='EncodeH3K36me3-sum')
    EncodeH3K36me3_max: float = Field(..., alias='EncodeH3K36me3-max')
    EncodeH3K79me2_sum: float = Field(..., alias='EncodeH3K79me2-sum')
    EncodeH3K79me2_max: float = Field(..., alias='EncodeH3K79me2-max')
    EncodeH4K20me1_sum: float = Field(..., alias='EncodeH4K20me1-sum')
    EncodeH4K20me1_max: float = Field(..., alias='EncodeH4K20me1-max')
    EncodeH2AFZ_sum: float = Field(..., alias='EncodeH2AFZ-sum')
    EncodeH2AFZ_max: float = Field(..., alias='EncodeH2AFZ-max')
    EncodeDNase_sum: float = Field(..., alias='EncodeDNase-sum')
    EncodeDNase_max: float = Field(..., alias='EncodeDNase-max')
    EncodetotalRNA_sum: float = Field(..., alias='EncodetotalRNA-sum')
    EncodetotalRNA_max: float = Field(..., alias='EncodetotalRNA-max')
    Grantham: int
    SpliceAI_acc_gain: int = Field(..., alias='SpliceAI-acc-gain')
    SpliceAI_acc_loss: int = Field(..., alias='SpliceAI-acc-loss')
    SpliceAI_don_gain: int = Field(..., alias='SpliceAI-don-gain')
    SpliceAI_don_loss: int = Field(..., alias='SpliceAI-don-loss')
    MMSp_acceptorIntron: int
    MMSp_acceptor: int
    MMSp_exon: int
    MMSp_donor: int
    MMSp_donorIntron: int
    Dist2Mutation: int
    Freq100bp: int
    Rare100bp: int
    Sngl100bp: int
    Freq1000bp: int
    Rare1000bp: int
    Sngl1000bp: int
    Freq10000bp: int
    Rare10000bp: int
    Sngl10000bp: int
    EnsembleRegulatoryFeature: None
    dbscSNV_ada_score: None = Field(..., alias='dbscSNV-ada_score')
    dbscSNV_rf_score: None = Field(..., alias='dbscSNV-rf_score')
    RemapOverlapTF: None
    RemapOverlapCL: None
    RawScore: float
    PHRED: float


class Dbsnp(BaseModel):
    chrom: str
    pos: int
    refAllele: str
    altAllele: str
    rsId: int


class Dbnsfp(BaseModel):
    chr: str
    pos_1_based_: int = Field(..., alias='pos(1-based)')
    ref: str
    alt: str
    aaref: str
    aaalt: str
    rs_dbSNP: str
    hg19_chr: str
    hg19_pos_1_based_: int = Field(..., alias='hg19_pos(1-based)')
    hg18_chr: str
    hg18_pos_1_based_: int = Field(..., alias='hg18_pos(1-based)')
    aapos: str
    genename: str
    Ensembl_geneid: str
    Ensembl_transcriptid: str
    Ensembl_proteinid: str
    Uniprot_acc: None
    Uniprot_entry: None
    HGVSc_ANNOVAR: str
    HGVSp_ANNOVAR: str
    HGVSc_snpEff: str
    HGVSp_snpEff: str
    HGVSc_VEP: str
    HGVSp_VEP: str
    APPRIS: str
    GENCODE_basic: str
    TSL: str
    VEP_canonical: str
    cds_strand: str
    refcodon: str
    codonpos: str
    codon_degeneracy: str
    Ancestral_allele: str
    AltaiNeandertal: str
    Denisova: str
    VindijiaNeandertal: str
    ChagyrskayaNeandertal: str
    SIFT_score: str
    SIFT_converted_rankscore: float
    SIFT_pred: str
    SIFT4G_score: str
    SIFT4G_converted_rankscore: float
    SIFT4G_pred: str
    Polyphen2_HDIV_score: None
    Polyphen2_HDIV_rankscore: None
    Polyphen2_HDIV_pred: None
    Polyphen2_HVAR_score: None
    Polyphen2_HVAR_rankscore: None
    Polyphen2_HVAR_pred: None
    LRT_score: None
    LRT_converted_rankscore: None
    LRT_pred: None
    LRT_Omega: None
    MutationTaster_score: str
    MutationTaster_converted_rankscore: float
    MutationTaster_pred: str
    MutationTaster_model: str
    MutationTaster_AAE: str
    MutationAssessor_score: None
    MutationAssessor_rankscore: None
    MutationAssessor_pred: None
    FATHMM_score: str
    FATHMM_converted_rankscore: float
    FATHMM_pred: str
    PROVEAN_score: str
    PROVEAN_converted_rankscore: float
    PROVEAN_pred: str
    VEST4_score: str
    VEST4_rankscore: float
    MetaSVM_score: float
    MetaSVM_rankscore: float
    MetaSVM_pred: str
    MetaLR_score: float
    MetaLR_rankscore: float
    MetaLR_pred: str
    Reliability_index: int
    MetaRNN_score: str
    MetaRNN_rankscore: float
    MetaRNN_pred: str
    M_CAP_score: None = Field(..., alias='M-CAP_score')
    M_CAP_rankscore: None = Field(..., alias='M-CAP_rankscore')
    M_CAP_pred: None = Field(..., alias='M-CAP_pred')
    REVEL_score: str
    REVEL_rankscore: float
    MutPred_score: str
    MutPred_rankscore: None
    MutPred_protID: str
    MutPred_AAchange: str
    MutPred_Top5features: str
    MVP_score: None
    MVP_rankscore: None
    gMVP_score: str
    gMVP_rankscore: float
    MPC_score: None
    MPC_rankscore: None
    PrimateAI_score: float
    PrimateAI_rankscore: float
    PrimateAI_pred: str
    DEOGEN2_score: None
    DEOGEN2_rankscore: None
    DEOGEN2_pred: None
    BayesDel_addAF_score: float
    BayesDel_addAF_rankscore: float
    BayesDel_addAF_pred: str
    BayesDel_noAF_score: float
    BayesDel_noAF_rankscore: float
    BayesDel_noAF_pred: str
    ClinPred_score: float
    ClinPred_rankscore: float
    ClinPred_pred: str
    LIST_S2_score: None = Field(..., alias='LIST-S2_score')
    LIST_S2_rankscore: None = Field(..., alias='LIST-S2_rankscore')
    LIST_S2_pred: None = Field(..., alias='LIST-S2_pred')
    VARITY_R_score: None
    VARITY_R_rankscore: None
    VARITY_ER_score: None
    VARITY_ER_rankscore: None
    VARITY_R_LOO_score: None
    VARITY_R_LOO_rankscore: None
    VARITY_ER_LOO_score: None
    VARITY_ER_LOO_rankscore: None
    ESM1b_score: None
    ESM1b_rankscore: None
    ESM1b_pred: None
    EVE_score: None
    EVE_rankscore: None
    EVE_Class10_pred: None
    EVE_Class20_pred: None
    EVE_Class25_pred: None
    EVE_Class30_pred: None
    EVE_Class40_pred: None
    EVE_Class50_pred: None
    EVE_Class60_pred: None
    EVE_Class70_pred: None
    EVE_Class75_pred: None
    EVE_Class80_pred: None
    EVE_Class90_pred: None
    AlphaMissense_score: str
    AlphaMissense_rankscore: float
    AlphaMissense_pred: str
    Aloft_Fraction_transcripts_affected: str
    Aloft_prob_Tolerant: str
    Aloft_prob_Recessive: str
    Aloft_prob_Dominant: str
    Aloft_pred: str
    Aloft_Confidence: str
    CADD_raw: float
    CADD_raw_rankscore: float
    CADD_phred: float
    CADD_raw_hg19: float
    CADD_raw_rankscore_hg19: float
    CADD_phred_hg19: float
    DANN_score: float
    DANN_rankscore: float
    fathmm_MKL_coding_score: float = Field(..., alias='fathmm-MKL_coding_score')
    fathmm_MKL_coding_rankscore: float = Field(..., alias='fathmm-MKL_coding_rankscore')
    fathmm_MKL_coding_pred: str = Field(..., alias='fathmm-MKL_coding_pred')
    fathmm_MKL_coding_group: str = Field(..., alias='fathmm-MKL_coding_group')
    fathmm_XF_coding_score: float = Field(..., alias='fathmm-XF_coding_score')
    fathmm_XF_coding_rankscore: float = Field(..., alias='fathmm-XF_coding_rankscore')
    fathmm_XF_coding_pred: str = Field(..., alias='fathmm-XF_coding_pred')
    Eigen_raw_coding: float = Field(..., alias='Eigen-raw_coding')
    Eigen_raw_coding_rankscore: float = Field(..., alias='Eigen-raw_coding_rankscore')
    Eigen_phred_coding: float = Field(..., alias='Eigen-phred_coding')
    Eigen_PC_raw_coding: float = Field(..., alias='Eigen-PC-raw_coding')
    Eigen_PC_raw_coding_rankscore: float = Field(
        ..., alias='Eigen-PC-raw_coding_rankscore'
    )
    Eigen_PC_phred_coding: float = Field(..., alias='Eigen-PC-phred_coding')
    GenoCanyon_score: float
    GenoCanyon_rankscore: float
    integrated_fitCons_score: float
    integrated_fitCons_rankscore: float
    integrated_confidence_value: int
    GM12878_fitCons_score: float
    GM12878_fitCons_rankscore: float
    GM12878_confidence_value: int
    H1_hESC_fitCons_score: float = Field(..., alias='H1-hESC_fitCons_score')
    H1_hESC_fitCons_rankscore: float = Field(..., alias='H1-hESC_fitCons_rankscore')
    H1_hESC_confidence_value: int = Field(..., alias='H1-hESC_confidence_value')
    HUVEC_fitCons_score: float
    HUVEC_fitCons_rankscore: float
    HUVEC_confidence_value: int
    LINSIGHT: None
    LINSIGHT_rankscore: None
    GERP___NR: float = Field(..., alias='GERP++_NR')
    GERP___RS: float = Field(..., alias='GERP++_RS')
    GERP___RS_rankscore: float = Field(..., alias='GERP++_RS_rankscore')
    phyloP100way_vertebrate: float
    phyloP100way_vertebrate_rankscore: float
    phyloP470way_mammalian: float
    phyloP470way_mammalian_rankscore: float
    phyloP17way_primate: float
    phyloP17way_primate_rankscore: float
    phastCons100way_vertebrate: float
    phastCons100way_vertebrate_rankscore: float
    phastCons470way_mammalian: int
    phastCons470way_mammalian_rankscore: float
    phastCons17way_primate: float
    phastCons17way_primate_rankscore: float
    SiPhy_29way_pi: str
    SiPhy_29way_logOdds: float
    SiPhy_29way_logOdds_rankscore: float
    bStatistic: int
    bStatistic_converted_rankscore: float
    field_1000Gp3_AC: int = Field(..., alias='1000Gp3_AC')
    field_1000Gp3_AF: float = Field(..., alias='1000Gp3_AF')
    field_1000Gp3_AFR_AC: int = Field(..., alias='1000Gp3_AFR_AC')
    field_1000Gp3_AFR_AF: float = Field(..., alias='1000Gp3_AFR_AF')
    field_1000Gp3_EUR_AC: int = Field(..., alias='1000Gp3_EUR_AC')
    field_1000Gp3_EUR_AF: float = Field(..., alias='1000Gp3_EUR_AF')
    field_1000Gp3_AMR_AC: int = Field(..., alias='1000Gp3_AMR_AC')
    field_1000Gp3_AMR_AF: float = Field(..., alias='1000Gp3_AMR_AF')
    field_1000Gp3_EAS_AC: int = Field(..., alias='1000Gp3_EAS_AC')
    field_1000Gp3_EAS_AF: int = Field(..., alias='1000Gp3_EAS_AF')
    field_1000Gp3_SAS_AC: int = Field(..., alias='1000Gp3_SAS_AC')
    field_1000Gp3_SAS_AF: float = Field(..., alias='1000Gp3_SAS_AF')
    TWINSUK_AC: int
    TWINSUK_AF: float
    ALSPAC_AC: int
    ALSPAC_AF: float
    UK10K_AC: int
    UK10K_AF: float
    ESP6500_AA_AC: int
    ESP6500_AA_AF: float
    ESP6500_EA_AC: int
    ESP6500_EA_AF: float
    ExAC_AC: int
    ExAC_AF: float
    ExAC_Adj_AC: int
    ExAC_Adj_AF: float
    ExAC_AFR_AC: int
    ExAC_AFR_AF: float
    ExAC_AMR_AC: int
    ExAC_AMR_AF: float
    ExAC_EAS_AC: int
    ExAC_EAS_AF: int
    ExAC_FIN_AC: int
    ExAC_FIN_AF: float
    ExAC_NFE_AC: int
    ExAC_NFE_AF: float
    ExAC_SAS_AC: int
    ExAC_SAS_AF: float
    ExAC_nonTCGA_AC: int
    ExAC_nonTCGA_AF: float
    ExAC_nonTCGA_Adj_AC: int
    ExAC_nonTCGA_Adj_AF: float
    ExAC_nonTCGA_AFR_AC: int
    ExAC_nonTCGA_AFR_AF: float
    ExAC_nonTCGA_AMR_AC: int
    ExAC_nonTCGA_AMR_AF: float
    ExAC_nonTCGA_EAS_AC: int
    ExAC_nonTCGA_EAS_AF: int
    ExAC_nonTCGA_FIN_AC: int
    ExAC_nonTCGA_FIN_AF: float
    ExAC_nonTCGA_NFE_AC: int
    ExAC_nonTCGA_NFE_AF: float
    ExAC_nonTCGA_SAS_AC: int
    ExAC_nonTCGA_SAS_AF: float
    ExAC_nonpsych_AC: int
    ExAC_nonpsych_AF: float
    ExAC_nonpsych_Adj_AC: int
    ExAC_nonpsych_Adj_AF: float
    ExAC_nonpsych_AFR_AC: int
    ExAC_nonpsych_AFR_AF: float
    ExAC_nonpsych_AMR_AC: int
    ExAC_nonpsych_AMR_AF: float
    ExAC_nonpsych_EAS_AC: int
    ExAC_nonpsych_EAS_AF: int
    ExAC_nonpsych_FIN_AC: int
    ExAC_nonpsych_FIN_AF: float
    ExAC_nonpsych_NFE_AC: int
    ExAC_nonpsych_NFE_AF: float
    ExAC_nonpsych_SAS_AC: int
    ExAC_nonpsych_SAS_AF: float
    gnomAD_exomes_flag: str
    gnomAD_exomes_AC: int
    gnomAD_exomes_AN: int
    gnomAD_exomes_AF: float
    gnomAD_exomes_nhomalt: int
    gnomAD_exomes_AFR_AC: int
    gnomAD_exomes_AFR_AN: int
    gnomAD_exomes_AFR_AF: float
    gnomAD_exomes_AFR_nhomalt: int
    gnomAD_exomes_AMR_AC: int
    gnomAD_exomes_AMR_AN: int
    gnomAD_exomes_AMR_AF: float
    gnomAD_exomes_AMR_nhomalt: int
    gnomAD_exomes_ASJ_AC: int
    gnomAD_exomes_ASJ_AN: int
    gnomAD_exomes_ASJ_AF: float
    gnomAD_exomes_ASJ_nhomalt: int
    gnomAD_exomes_EAS_AC: int
    gnomAD_exomes_EAS_AN: int
    gnomAD_exomes_EAS_AF: float
    gnomAD_exomes_EAS_nhomalt: int
    gnomAD_exomes_FIN_AC: int
    gnomAD_exomes_FIN_AN: int
    gnomAD_exomes_FIN_AF: float
    gnomAD_exomes_FIN_nhomalt: int
    gnomAD_exomes_NFE_AC: int
    gnomAD_exomes_NFE_AN: int
    gnomAD_exomes_NFE_AF: float
    gnomAD_exomes_NFE_nhomalt: int
    gnomAD_exomes_SAS_AC: int
    gnomAD_exomes_SAS_AN: int
    gnomAD_exomes_SAS_AF: float
    gnomAD_exomes_SAS_nhomalt: int
    gnomAD_exomes_POPMAX_AC: int
    gnomAD_exomes_POPMAX_AN: int
    gnomAD_exomes_POPMAX_AF: float
    gnomAD_exomes_POPMAX_nhomalt: int
    gnomAD_exomes_controls_AC: int
    gnomAD_exomes_controls_AN: int
    gnomAD_exomes_controls_AF: float
    gnomAD_exomes_controls_nhomalt: int
    gnomAD_exomes_non_neuro_AC: int
    gnomAD_exomes_non_neuro_AN: int
    gnomAD_exomes_non_neuro_AF: float
    gnomAD_exomes_non_neuro_nhomalt: int
    gnomAD_exomes_non_cancer_AC: int
    gnomAD_exomes_non_cancer_AN: int
    gnomAD_exomes_non_cancer_AF: float
    gnomAD_exomes_non_cancer_nhomalt: int
    gnomAD_exomes_non_topmed_AC: int
    gnomAD_exomes_non_topmed_AN: int
    gnomAD_exomes_non_topmed_AF: float
    gnomAD_exomes_non_topmed_nhomalt: int
    gnomAD_exomes_controls_AFR_AC: int
    gnomAD_exomes_controls_AFR_AN: int
    gnomAD_exomes_controls_AFR_AF: float
    gnomAD_exomes_controls_AFR_nhomalt: int
    gnomAD_exomes_controls_AMR_AC: int
    gnomAD_exomes_controls_AMR_AN: int
    gnomAD_exomes_controls_AMR_AF: float
    gnomAD_exomes_controls_AMR_nhomalt: int
    gnomAD_exomes_controls_ASJ_AC: int
    gnomAD_exomes_controls_ASJ_AN: int
    gnomAD_exomes_controls_ASJ_AF: float
    gnomAD_exomes_controls_ASJ_nhomalt: int
    gnomAD_exomes_controls_EAS_AC: int
    gnomAD_exomes_controls_EAS_AN: int
    gnomAD_exomes_controls_EAS_AF: float
    gnomAD_exomes_controls_EAS_nhomalt: int
    gnomAD_exomes_controls_FIN_AC: int
    gnomAD_exomes_controls_FIN_AN: int
    gnomAD_exomes_controls_FIN_AF: float
    gnomAD_exomes_controls_FIN_nhomalt: int
    gnomAD_exomes_controls_NFE_AC: int
    gnomAD_exomes_controls_NFE_AN: int
    gnomAD_exomes_controls_NFE_AF: float
    gnomAD_exomes_controls_NFE_nhomalt: int
    gnomAD_exomes_controls_SAS_AC: int
    gnomAD_exomes_controls_SAS_AN: int
    gnomAD_exomes_controls_SAS_AF: float
    gnomAD_exomes_controls_SAS_nhomalt: int
    gnomAD_exomes_controls_POPMAX_AC: int
    gnomAD_exomes_controls_POPMAX_AN: int
    gnomAD_exomes_controls_POPMAX_AF: float
    gnomAD_exomes_controls_POPMAX_nhomalt: int
    gnomAD_exomes_non_neuro_AFR_AC: int
    gnomAD_exomes_non_neuro_AFR_AN: int
    gnomAD_exomes_non_neuro_AFR_AF: float
    gnomAD_exomes_non_neuro_AFR_nhomalt: int
    gnomAD_exomes_non_neuro_AMR_AC: int
    gnomAD_exomes_non_neuro_AMR_AN: int
    gnomAD_exomes_non_neuro_AMR_AF: float
    gnomAD_exomes_non_neuro_AMR_nhomalt: int
    gnomAD_exomes_non_neuro_ASJ_AC: int
    gnomAD_exomes_non_neuro_ASJ_AN: int
    gnomAD_exomes_non_neuro_ASJ_AF: float
    gnomAD_exomes_non_neuro_ASJ_nhomalt: int
    gnomAD_exomes_non_neuro_EAS_AC: int
    gnomAD_exomes_non_neuro_EAS_AN: int
    gnomAD_exomes_non_neuro_EAS_AF: float
    gnomAD_exomes_non_neuro_EAS_nhomalt: int
    gnomAD_exomes_non_neuro_FIN_AC: int
    gnomAD_exomes_non_neuro_FIN_AN: int
    gnomAD_exomes_non_neuro_FIN_AF: float
    gnomAD_exomes_non_neuro_FIN_nhomalt: int
    gnomAD_exomes_non_neuro_NFE_AC: int
    gnomAD_exomes_non_neuro_NFE_AN: int
    gnomAD_exomes_non_neuro_NFE_AF: float
    gnomAD_exomes_non_neuro_NFE_nhomalt: int
    gnomAD_exomes_non_neuro_SAS_AC: int
    gnomAD_exomes_non_neuro_SAS_AN: int
    gnomAD_exomes_non_neuro_SAS_AF: float
    gnomAD_exomes_non_neuro_SAS_nhomalt: int
    gnomAD_exomes_non_neuro_POPMAX_AC: int
    gnomAD_exomes_non_neuro_POPMAX_AN: int
    gnomAD_exomes_non_neuro_POPMAX_AF: float
    gnomAD_exomes_non_neuro_POPMAX_nhomalt: int
    gnomAD_exomes_non_cancer_AFR_AC: int
    gnomAD_exomes_non_cancer_AFR_AN: int
    gnomAD_exomes_non_cancer_AFR_AF: float
    gnomAD_exomes_non_cancer_AFR_nhomalt: int
    gnomAD_exomes_non_cancer_AMR_AC: int
    gnomAD_exomes_non_cancer_AMR_AN: int
    gnomAD_exomes_non_cancer_AMR_AF: float
    gnomAD_exomes_non_cancer_AMR_nhomalt: int
    gnomAD_exomes_non_cancer_ASJ_AC: int
    gnomAD_exomes_non_cancer_ASJ_AN: int
    gnomAD_exomes_non_cancer_ASJ_AF: float
    gnomAD_exomes_non_cancer_ASJ_nhomalt: int
    gnomAD_exomes_non_cancer_EAS_AC: int
    gnomAD_exomes_non_cancer_EAS_AN: int
    gnomAD_exomes_non_cancer_EAS_AF: float
    gnomAD_exomes_non_cancer_EAS_nhomalt: int
    gnomAD_exomes_non_cancer_FIN_AC: int
    gnomAD_exomes_non_cancer_FIN_AN: int
    gnomAD_exomes_non_cancer_FIN_AF: float
    gnomAD_exomes_non_cancer_FIN_nhomalt: int
    gnomAD_exomes_non_cancer_NFE_AC: int
    gnomAD_exomes_non_cancer_NFE_AN: int
    gnomAD_exomes_non_cancer_NFE_AF: float
    gnomAD_exomes_non_cancer_NFE_nhomalt: int
    gnomAD_exomes_non_cancer_SAS_AC: int
    gnomAD_exomes_non_cancer_SAS_AN: int
    gnomAD_exomes_non_cancer_SAS_AF: float
    gnomAD_exomes_non_cancer_SAS_nhomalt: int
    gnomAD_exomes_non_cancer_POPMAX_AC: int
    gnomAD_exomes_non_cancer_POPMAX_AN: int
    gnomAD_exomes_non_cancer_POPMAX_AF: float
    gnomAD_exomes_non_cancer_POPMAX_nhomalt: int
    gnomAD_exomes_non_topmed_AFR_AC: int
    gnomAD_exomes_non_topmed_AFR_AN: int
    gnomAD_exomes_non_topmed_AFR_AF: float
    gnomAD_exomes_non_topmed_AFR_nhomalt: int
    gnomAD_exomes_non_topmed_AMR_AC: int
    gnomAD_exomes_non_topmed_AMR_AN: int
    gnomAD_exomes_non_topmed_AMR_AF: float
    gnomAD_exomes_non_topmed_AMR_nhomalt: int
    gnomAD_exomes_non_topmed_ASJ_AC: int
    gnomAD_exomes_non_topmed_ASJ_AN: int
    gnomAD_exomes_non_topmed_ASJ_AF: float
    gnomAD_exomes_non_topmed_ASJ_nhomalt: int
    gnomAD_exomes_non_topmed_EAS_AC: int
    gnomAD_exomes_non_topmed_EAS_AN: int
    gnomAD_exomes_non_topmed_EAS_AF: float
    gnomAD_exomes_non_topmed_EAS_nhomalt: int
    gnomAD_exomes_non_topmed_FIN_AC: int
    gnomAD_exomes_non_topmed_FIN_AN: int
    gnomAD_exomes_non_topmed_FIN_AF: float
    gnomAD_exomes_non_topmed_FIN_nhomalt: int
    gnomAD_exomes_non_topmed_NFE_AC: int
    gnomAD_exomes_non_topmed_NFE_AN: int
    gnomAD_exomes_non_topmed_NFE_AF: float
    gnomAD_exomes_non_topmed_NFE_nhomalt: int
    gnomAD_exomes_non_topmed_SAS_AC: int
    gnomAD_exomes_non_topmed_SAS_AN: int
    gnomAD_exomes_non_topmed_SAS_AF: float
    gnomAD_exomes_non_topmed_SAS_nhomalt: int
    gnomAD_exomes_non_topmed_POPMAX_AC: int
    gnomAD_exomes_non_topmed_POPMAX_AN: int
    gnomAD_exomes_non_topmed_POPMAX_AF: float
    gnomAD_exomes_non_topmed_POPMAX_nhomalt: int
    gnomAD_genomes_flag: None
    gnomAD_genomes_AC: int
    gnomAD_genomes_AN: int
    gnomAD_genomes_AF: float
    gnomAD_genomes_nhomalt: int
    gnomAD_genomes_POPMAX_AC: int
    gnomAD_genomes_POPMAX_AN: int
    gnomAD_genomes_POPMAX_AF: float
    gnomAD_genomes_POPMAX_nhomalt: int
    gnomAD_genomes_AFR_AC: int
    gnomAD_genomes_AFR_AN: int
    gnomAD_genomes_AFR_AF: float
    gnomAD_genomes_AFR_nhomalt: int
    gnomAD_genomes_AMI_AC: int
    gnomAD_genomes_AMI_AN: int
    gnomAD_genomes_AMI_AF: float
    gnomAD_genomes_AMI_nhomalt: int
    gnomAD_genomes_AMR_AC: int
    gnomAD_genomes_AMR_AN: int
    gnomAD_genomes_AMR_AF: float
    gnomAD_genomes_AMR_nhomalt: int
    gnomAD_genomes_ASJ_AC: int
    gnomAD_genomes_ASJ_AN: int
    gnomAD_genomes_ASJ_AF: float
    gnomAD_genomes_ASJ_nhomalt: int
    gnomAD_genomes_EAS_AC: int
    gnomAD_genomes_EAS_AN: int
    gnomAD_genomes_EAS_AF: float
    gnomAD_genomes_EAS_nhomalt: int
    gnomAD_genomes_FIN_AC: int
    gnomAD_genomes_FIN_AN: int
    gnomAD_genomes_FIN_AF: float
    gnomAD_genomes_FIN_nhomalt: int
    gnomAD_genomes_MID_AC: int
    gnomAD_genomes_MID_AN: int
    gnomAD_genomes_MID_AF: float
    gnomAD_genomes_MID_nhomalt: int
    gnomAD_genomes_NFE_AC: int
    gnomAD_genomes_NFE_AN: int
    gnomAD_genomes_NFE_AF: float
    gnomAD_genomes_NFE_nhomalt: int
    gnomAD_genomes_SAS_AC: int
    gnomAD_genomes_SAS_AN: int
    gnomAD_genomes_SAS_AF: float
    gnomAD_genomes_SAS_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_AC: int
    gnomAD_genomes_controls_and_biobanks_AN: int
    gnomAD_genomes_controls_and_biobanks_AF: float
    gnomAD_genomes_controls_and_biobanks_nhomalt: int
    gnomAD_genomes_non_neuro_AC: int
    gnomAD_genomes_non_neuro_AN: int
    gnomAD_genomes_non_neuro_AF: float
    gnomAD_genomes_non_neuro_nhomalt: int
    gnomAD_genomes_non_cancer_AC: int
    gnomAD_genomes_non_cancer_AN: int
    gnomAD_genomes_non_cancer_AF: float
    gnomAD_genomes_non_cancer_nhomalt: int
    gnomAD_genomes_non_topmed_AC: int
    gnomAD_genomes_non_topmed_AN: int
    gnomAD_genomes_non_topmed_AF: float
    gnomAD_genomes_non_topmed_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_AFR_AC: int
    gnomAD_genomes_controls_and_biobanks_AFR_AN: int
    gnomAD_genomes_controls_and_biobanks_AFR_AF: float
    gnomAD_genomes_controls_and_biobanks_AFR_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_AMI_AC: int
    gnomAD_genomes_controls_and_biobanks_AMI_AN: int
    gnomAD_genomes_controls_and_biobanks_AMI_AF: float
    gnomAD_genomes_controls_and_biobanks_AMI_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_AMR_AC: int
    gnomAD_genomes_controls_and_biobanks_AMR_AN: int
    gnomAD_genomes_controls_and_biobanks_AMR_AF: float
    gnomAD_genomes_controls_and_biobanks_AMR_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_ASJ_AC: int
    gnomAD_genomes_controls_and_biobanks_ASJ_AN: int
    gnomAD_genomes_controls_and_biobanks_ASJ_AF: float
    gnomAD_genomes_controls_and_biobanks_ASJ_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_EAS_AC: int
    gnomAD_genomes_controls_and_biobanks_EAS_AN: int
    gnomAD_genomes_controls_and_biobanks_EAS_AF: float
    gnomAD_genomes_controls_and_biobanks_EAS_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_FIN_AC: int
    gnomAD_genomes_controls_and_biobanks_FIN_AN: int
    gnomAD_genomes_controls_and_biobanks_FIN_AF: float
    gnomAD_genomes_controls_and_biobanks_FIN_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_MID_AC: int
    gnomAD_genomes_controls_and_biobanks_MID_AN: int
    gnomAD_genomes_controls_and_biobanks_MID_AF: float
    gnomAD_genomes_controls_and_biobanks_MID_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_NFE_AC: int
    gnomAD_genomes_controls_and_biobanks_NFE_AN: int
    gnomAD_genomes_controls_and_biobanks_NFE_AF: float
    gnomAD_genomes_controls_and_biobanks_NFE_nhomalt: int
    gnomAD_genomes_controls_and_biobanks_SAS_AC: int
    gnomAD_genomes_controls_and_biobanks_SAS_AN: int
    gnomAD_genomes_controls_and_biobanks_SAS_AF: float
    gnomAD_genomes_controls_and_biobanks_SAS_nhomalt: int
    gnomAD_genomes_non_neuro_AFR_AC: int
    gnomAD_genomes_non_neuro_AFR_AN: int
    gnomAD_genomes_non_neuro_AFR_AF: float
    gnomAD_genomes_non_neuro_AFR_nhomalt: int
    gnomAD_genomes_non_neuro_AMI_AC: int
    gnomAD_genomes_non_neuro_AMI_AN: int
    gnomAD_genomes_non_neuro_AMI_AF: float
    gnomAD_genomes_non_neuro_AMI_nhomalt: int
    gnomAD_genomes_non_neuro_AMR_AC: int
    gnomAD_genomes_non_neuro_AMR_AN: int
    gnomAD_genomes_non_neuro_AMR_AF: float
    gnomAD_genomes_non_neuro_AMR_nhomalt: int
    gnomAD_genomes_non_neuro_ASJ_AC: int
    gnomAD_genomes_non_neuro_ASJ_AN: int
    gnomAD_genomes_non_neuro_ASJ_AF: float
    gnomAD_genomes_non_neuro_ASJ_nhomalt: int
    gnomAD_genomes_non_neuro_EAS_AC: int
    gnomAD_genomes_non_neuro_EAS_AN: int
    gnomAD_genomes_non_neuro_EAS_AF: float
    gnomAD_genomes_non_neuro_EAS_nhomalt: int
    gnomAD_genomes_non_neuro_FIN_AC: int
    gnomAD_genomes_non_neuro_FIN_AN: int
    gnomAD_genomes_non_neuro_FIN_AF: float
    gnomAD_genomes_non_neuro_FIN_nhomalt: int
    gnomAD_genomes_non_neuro_MID_AC: int
    gnomAD_genomes_non_neuro_MID_AN: int
    gnomAD_genomes_non_neuro_MID_AF: float
    gnomAD_genomes_non_neuro_MID_nhomalt: int
    gnomAD_genomes_non_neuro_NFE_AC: int
    gnomAD_genomes_non_neuro_NFE_AN: int
    gnomAD_genomes_non_neuro_NFE_AF: float
    gnomAD_genomes_non_neuro_NFE_nhomalt: int
    gnomAD_genomes_non_neuro_SAS_AC: int
    gnomAD_genomes_non_neuro_SAS_AN: int
    gnomAD_genomes_non_neuro_SAS_AF: float
    gnomAD_genomes_non_neuro_SAS_nhomalt: int
    gnomAD_genomes_non_cancer_AFR_AC: int
    gnomAD_genomes_non_cancer_AFR_AN: int
    gnomAD_genomes_non_cancer_AFR_AF: float
    gnomAD_genomes_non_cancer_AFR_nhomalt: int
    gnomAD_genomes_non_cancer_AMI_AC: int
    gnomAD_genomes_non_cancer_AMI_AN: int
    gnomAD_genomes_non_cancer_AMI_AF: float
    gnomAD_genomes_non_cancer_AMI_nhomalt: int
    gnomAD_genomes_non_cancer_AMR_AC: int
    gnomAD_genomes_non_cancer_AMR_AN: int
    gnomAD_genomes_non_cancer_AMR_AF: float
    gnomAD_genomes_non_cancer_AMR_nhomalt: int
    gnomAD_genomes_non_cancer_ASJ_AC: int
    gnomAD_genomes_non_cancer_ASJ_AN: int
    gnomAD_genomes_non_cancer_ASJ_AF: float
    gnomAD_genomes_non_cancer_ASJ_nhomalt: int
    gnomAD_genomes_non_cancer_EAS_AC: int
    gnomAD_genomes_non_cancer_EAS_AN: int
    gnomAD_genomes_non_cancer_EAS_AF: float
    gnomAD_genomes_non_cancer_EAS_nhomalt: int
    gnomAD_genomes_non_cancer_FIN_AC: int
    gnomAD_genomes_non_cancer_FIN_AN: int
    gnomAD_genomes_non_cancer_FIN_AF: float
    gnomAD_genomes_non_cancer_FIN_nhomalt: int
    gnomAD_genomes_non_cancer_MID_AC: int
    gnomAD_genomes_non_cancer_MID_AN: int
    gnomAD_genomes_non_cancer_MID_AF: float
    gnomAD_genomes_non_cancer_MID_nhomalt: int
    gnomAD_genomes_non_cancer_NFE_AC: int
    gnomAD_genomes_non_cancer_NFE_AN: int
    gnomAD_genomes_non_cancer_NFE_AF: float
    gnomAD_genomes_non_cancer_NFE_nhomalt: int
    gnomAD_genomes_non_cancer_SAS_AC: int
    gnomAD_genomes_non_cancer_SAS_AN: int
    gnomAD_genomes_non_cancer_SAS_AF: float
    gnomAD_genomes_non_cancer_SAS_nhomalt: int
    gnomAD_genomes_non_topmed_AFR_AC: int
    gnomAD_genomes_non_topmed_AFR_AN: int
    gnomAD_genomes_non_topmed_AFR_AF: float
    gnomAD_genomes_non_topmed_AFR_nhomalt: int
    gnomAD_genomes_non_topmed_AMI_AC: int
    gnomAD_genomes_non_topmed_AMI_AN: int
    gnomAD_genomes_non_topmed_AMI_AF: float
    gnomAD_genomes_non_topmed_AMI_nhomalt: int
    gnomAD_genomes_non_topmed_AMR_AC: int
    gnomAD_genomes_non_topmed_AMR_AN: int
    gnomAD_genomes_non_topmed_AMR_AF: float
    gnomAD_genomes_non_topmed_AMR_nhomalt: int
    gnomAD_genomes_non_topmed_ASJ_AC: int
    gnomAD_genomes_non_topmed_ASJ_AN: int
    gnomAD_genomes_non_topmed_ASJ_AF: float
    gnomAD_genomes_non_topmed_ASJ_nhomalt: int
    gnomAD_genomes_non_topmed_EAS_AC: int
    gnomAD_genomes_non_topmed_EAS_AN: int
    gnomAD_genomes_non_topmed_EAS_AF: float
    gnomAD_genomes_non_topmed_EAS_nhomalt: int
    gnomAD_genomes_non_topmed_FIN_AC: int
    gnomAD_genomes_non_topmed_FIN_AN: int
    gnomAD_genomes_non_topmed_FIN_AF: float
    gnomAD_genomes_non_topmed_FIN_nhomalt: int
    gnomAD_genomes_non_topmed_MID_AC: int
    gnomAD_genomes_non_topmed_MID_AN: int
    gnomAD_genomes_non_topmed_MID_AF: float
    gnomAD_genomes_non_topmed_MID_nhomalt: int
    gnomAD_genomes_non_topmed_NFE_AC: int
    gnomAD_genomes_non_topmed_NFE_AN: int
    gnomAD_genomes_non_topmed_NFE_AF: float
    gnomAD_genomes_non_topmed_NFE_nhomalt: int
    gnomAD_genomes_non_topmed_SAS_AC: int
    gnomAD_genomes_non_topmed_SAS_AN: int
    gnomAD_genomes_non_topmed_SAS_AF: float
    gnomAD_genomes_non_topmed_SAS_nhomalt: int
    ALFA_European_AC: int
    ALFA_European_AN: int
    ALFA_European_AF: float
    ALFA_African_Others_AC: int
    ALFA_African_Others_AN: int
    ALFA_African_Others_AF: int
    ALFA_East_Asian_AC: int
    ALFA_East_Asian_AN: int
    ALFA_East_Asian_AF: float
    ALFA_African_American_AC: int
    ALFA_African_American_AN: int
    ALFA_African_American_AF: float
    ALFA_Latin_American_1_AC: int
    ALFA_Latin_American_1_AN: int
    ALFA_Latin_American_1_AF: float
    ALFA_Latin_American_2_AC: int
    ALFA_Latin_American_2_AN: int
    ALFA_Latin_American_2_AF: float
    ALFA_Other_Asian_AC: int
    ALFA_Other_Asian_AN: int
    ALFA_Other_Asian_AF: float
    ALFA_South_Asian_AC: int
    ALFA_South_Asian_AN: int
    ALFA_South_Asian_AF: float
    ALFA_Other_AC: int
    ALFA_Other_AN: int
    ALFA_Other_AF: float
    ALFA_African_AC: int
    ALFA_African_AN: int
    ALFA_African_AF: float
    ALFA_Asian_AC: int
    ALFA_Asian_AN: int
    ALFA_Asian_AF: float
    ALFA_Total_AC: int
    ALFA_Total_AN: int
    ALFA_Total_AF: float
    clinvar_id: None
    clinvar_clnsig: None
    clinvar_trait: None
    clinvar_review: None
    clinvar_hgvs: None
    clinvar_var_source: None
    clinvar_MedGen_id: None
    clinvar_OMIM_id: None
    clinvar_Orphanet_id: None
    Interpro_domain: None
    GTEx_V8_gene: str
    GTEx_V8_tissue: str
    Geuvadis_eQTL_target_gene: None


class Overall(BaseModel):
    ac: int
    an: int
    nhomalt: Optional[int] = None
    af: float


class Xx(BaseModel):
    ac: int
    an: int
    nhomalt: Optional[int] = None
    af: float


class Xy(BaseModel):
    ac: int
    an: int
    nhomalt: Optional[int] = None
    af: float


class Counts(BaseModel):
    overall: Overall
    xx: Xx
    xy: Xy


class ByAncestryGroupItem(BaseModel):
    ancestryGroup: str
    counts: Counts
    faf95: Optional[float] = None
    faf99: Optional[float] = None


class Overall1(BaseModel):
    ac: int
    an: int
    nhomalt: int
    af: float


class Xx1(BaseModel):
    ac: int
    an: int
    nhomalt: int
    af: float


class Xy1(BaseModel):
    ac: int
    an: int
    nhomalt: int
    af: float


class BySex(BaseModel):
    overall: Overall1
    xx: Xx1
    xy: Xy1


class Raw(BaseModel):
    ac: int
    an: int
    nhomalt: int
    af: float


class AlleleCount(BaseModel):
    cohort: Optional[str] = None
    byAncestryGroup: List[ByAncestryGroupItem]
    bySex: BySex
    raw: Raw
    grpmax: str
    afGrpmax: float
    acGrpmax: int
    anGrpmax: int
    nhomaltGrpmax: int


class EffectInfo(BaseModel):
    pangolinLargestDs: int
    phylop: float
    polyphenMax: float
    revelMax: float
    siftMax: float
    spliceaiDsMax: int
    caddPhred: float


class VariantInfo(BaseModel):
    variantType: str
    alleleType: str
    nAltAlleles: int
    varDp: int
    asVardp: int


class QualityInfo(BaseModel):
    asFs: float
    asMq: float
    mqRankSum: int
    asMqRankSum: int
    asQd: float
    readPosRankSum: float
    asReadPosRankSum: float
    asSor: float
    positiveTrainSite: bool
    asVqslod: float
    asCulprit: str
    asPabMax: int
    asQualApprox: int
    asSbTable: str
    sor: float


class AgeInfo(BaseModel):
    ageHistHomNSmaller: int
    ageHistHomNLarger: int
    ageHistHetNSmaller: int
    ageHistHetNLarger: int


class VrsInfo(BaseModel):
    alleleIds: List[str]
    ends: List[int]
    starts: List[int]
    states: List[str]


class GnomadExomes(BaseModel):
    chrom: str
    pos: int
    refAllele: str
    altAllele: str
    alleleCounts: List[AlleleCount]
    effectInfo: EffectInfo
    variantInfo: VariantInfo
    qualityInfo: QualityInfo
    ageInfo: AgeInfo
    vrsInfo: VrsInfo


class Overall2(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    nhomalt: Optional[int] = None
    af: Optional[float] = None


class Xx2(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    nhomalt: Optional[int] = None
    af: Optional[float] = None


class Xy2(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    nhomalt: Optional[int] = None
    af: Optional[float] = None


class Counts1(BaseModel):
    overall: Overall2
    xx: Xx2
    xy: Xy2


class ByAncestryGroupItem1(BaseModel):
    ancestryGroup: str
    counts: Counts1
    faf95: Optional[float] = None
    faf99: Optional[float] = None


class BySex1(BaseModel):
    overall: Overall2
    xx: Xx2
    xy: Xy2


class Raw1(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    nhomalt: Optional[int] = None
    af: Optional[float] = None


class AlleleCount1(BaseModel):
    cohort: Optional[str] = None
    byAncestryGroup: List[ByAncestryGroupItem1]
    bySex: BySex1
    raw: Raw1
    grpmax: Optional[str] = None
    afGrpmax: Optional[float] = None
    acGrpmax: Optional[int] = None
    anGrpmax: Optional[int] = None
    nhomaltGrpmax: Optional[int] = None


class QualityInfo1(BaseModel):
    asFs: int
    asMq: float
    mqRankSum: int
    asMqRankSum: float
    asQd: float
    readPosRankSum: float
    asReadPosRankSum: float
    asSor: float
    positiveTrainSite: bool
    asVqslod: float
    asCulprit: str
    asPabMax: int
    asQualApprox: int
    asSbTable: str
    sor: float


class GnomadGenomes(BaseModel):
    chrom: str
    pos: int
    refAllele: str
    altAllele: str
    alleleCounts: List[AlleleCount1]
    effectInfo: EffectInfo
    variantInfo: VariantInfo
    qualityInfo: QualityInfo1
    ageInfo: AgeInfo
    vrsInfo: VrsInfo


class Record(BaseModel):
    chrom: str
    start: int
    stop: int
    hgncId: str
    enstId: str
    exonNum: int
    exonCount: int
    alignment: str


class UcscConservationItem(BaseModel):
    records: List[Record]


class Result(BaseModel):
    cadd: Cadd
    dbsnp: Dbsnp
    dbnsfp: Dbnsfp
    dbscsnv: None
    gnomad_mtdna: None
    gnomad_exomes: GnomadExomes
    gnomad_genomes: GnomadGenomes
    helixmtdb: None
    ucsc_conservation: List[UcscConservationItem]
    clinvar: None


class Model(BaseModel):
    server_version: str
    query: Query
    result: Result
