# generated by datamodel-codegen:
#   filename:  ex.json
#   timestamp: 2024-03-20T16:15:51+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class NM0012670392(BaseModel):
    seqvar: str
    gene: str


class NM0013709741(BaseModel):
    seqvar: str
    gene: str


class Model(BaseModel):
    NM_001267039_2: NM0012670392 = Field(..., alias='NM_001267039.2')
    NM_001370974_1: NM0013709741 = Field(..., alias='NM_001370974.1')
