# generated by datamodel-codegen:
#   filename:  annonars_range_success.json
#   timestamp: 2024-06-11T07:57:54+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Query(BaseModel):
    genome_release: str
    chromosome: str
    start: int
    stop: int


class Cadd(BaseModel):
    Chrom: str
    Pos: int
    Ref: str
    Alt: str
    Type: str
    Length: int
    AnnoType: str
    Consequence: str
    ConsScore: int
    ConsDetail: str
    GC: float
    CpG: float
    motifECount: None
    motifEName: None
    motifEHIPos: None
    motifEScoreChng: None
    oAA: None
    nAA: None
    GeneID: str
    FeatureID: str
    GeneName: str
    CCDS: str
    Intron: None
    Exon: str
    cDNApos: int
    relcDNApos: float
    CDSpos: None
    relCDSpos: None
    protPos: None
    relProtPos: None
    Domain: None
    Dst2Splice: None
    Dst2SplType: None
    minDistTSS: int
    minDistTSE: int
    SIFTcat: None
    SIFTval: None
    PolyPhenCat: None
    PolyPhenVal: None
    priPhCons: float
    mamPhCons: int
    verPhCons: int
    priPhyloP: float
    mamPhyloP: float
    verPhyloP: float
    bStatistic: int
    targetScan: None
    mirSVR_Score: None = Field(..., alias="mirSVR-Score")
    mirSVR_E: None = Field(..., alias="mirSVR-E")
    mirSVR_Aln: None = Field(..., alias="mirSVR-Aln")
    cHmmTssA: int
    cHmmTssAFlnk: int
    cHmmTxFlnk: int
    cHmmTx: int
    cHmmTxWk: float
    cHmmEnhG: int
    cHmmEnh: int
    cHmmZnfRpts: int
    cHmmHet: int
    cHmmTssBiv: int
    cHmmBivFlnk: int
    cHmmEnhBiv: float
    cHmmReprPC: float
    cHmmReprPCWk: float
    cHmmQuies: float
    GerpRS: None
    GerpRSpval: None
    GerpN: float
    GerpS: float
    TFBS: None
    TFBSPeaks: None
    TFBSPeaksMax: None
    tOverlapMotifs: None
    motifDist: None
    Segway: str
    EncH3K27Ac: int
    EncH3K4Me1: float
    EncH3K4Me3: float
    EncExp: None
    EncNucleo: float
    EncOCC: int
    EncOCCombPVal: float
    EncOCDNasePVal: float
    EncOCFairePVal: float
    EncOCpolIIPVal: int
    EncOCctcfPVal: int
    EncOCmycPVal: float
    EncOCDNaseSig: float
    EncOCFaireSig: float
    EncOCpolIISig: int
    EncOCctcfSig: float
    EncOCmycSig: float
    Grantham: None
    SpliceAI_acc_gain: int = Field(..., alias="SpliceAI-acc-gain")
    SpliceAI_acc_loss: int = Field(..., alias="SpliceAI-acc-loss")
    SpliceAI_don_gain: int = Field(..., alias="SpliceAI-don-gain")
    SpliceAI_don_loss: int = Field(..., alias="SpliceAI-don-loss")
    MMSp_acceptorIntron: float
    MMSp_acceptor: int
    MMSp_exon: int
    MMSp_donor: int
    MMSp_donorIntron: int
    Dist2Mutation: int
    Freq100bp: int
    Rare100bp: int
    Sngl100bp: int
    Freq1000bp: int
    Rare1000bp: int
    Sngl1000bp: int
    Freq10000bp: int
    Rare10000bp: int
    Sngl10000bp: int
    dbscSNV_ada_score: None = Field(..., alias="dbscSNV-ada_score")
    dbscSNV_rf_score: None = Field(..., alias="dbscSNV-rf_score")
    RawScore: float
    PHRED: float


class DbsnpItem(BaseModel):
    chrom: str
    pos: int
    refAllele: str
    altAllele: str
    rsId: int


class Dbnsfp(BaseModel):
    chr: str
    pos_1_based_: int = Field(..., alias="pos(1-based)")
    ref: str
    alt: str
    aaref: str
    aaalt: str
    rs_dbSNP: None
    hg19_chr: str
    hg19_pos_1_based_: int = Field(..., alias="hg19_pos(1-based)")
    hg18_chr: str
    hg18_pos_1_based_: int = Field(..., alias="hg18_pos(1-based)")
    aapos: str
    genename: str
    Ensembl_geneid: str
    Ensembl_transcriptid: str
    Ensembl_proteinid: str
    Uniprot_acc: str
    Uniprot_entry: str
    HGVSc_ANNOVAR: str
    HGVSp_ANNOVAR: str
    HGVSc_snpEff: str
    HGVSp_snpEff: str
    HGVSc_VEP: str
    HGVSp_VEP: str
    APPRIS: str
    GENCODE_basic: str
    TSL: str
    VEP_canonical: str
    cds_strand: str
    refcodon: str
    codonpos: str
    codon_degeneracy: str
    Ancestral_allele: str
    AltaiNeandertal: str
    Denisova: str
    VindijiaNeandertal: str
    ChagyrskayaNeandertal: str
    SIFT_score: None
    SIFT_converted_rankscore: None
    SIFT_pred: None
    SIFT4G_score: None
    SIFT4G_converted_rankscore: None
    SIFT4G_pred: None
    Polyphen2_HDIV_score: None
    Polyphen2_HDIV_rankscore: None
    Polyphen2_HDIV_pred: None
    Polyphen2_HVAR_score: None
    Polyphen2_HVAR_rankscore: None
    Polyphen2_HVAR_pred: None
    LRT_score: None
    LRT_converted_rankscore: None
    LRT_pred: None
    LRT_Omega: None
    MutationTaster_score: str
    MutationTaster_converted_rankscore: float
    MutationTaster_pred: str
    MutationTaster_model: str
    MutationTaster_AAE: str
    MutationAssessor_score: None
    MutationAssessor_rankscore: None
    MutationAssessor_pred: None
    FATHMM_score: None
    FATHMM_converted_rankscore: None
    FATHMM_pred: None
    PROVEAN_score: None
    PROVEAN_converted_rankscore: None
    PROVEAN_pred: None
    VEST4_score: str
    VEST4_rankscore: float
    MetaSVM_score: None
    MetaSVM_rankscore: None
    MetaSVM_pred: None
    MetaLR_score: None
    MetaLR_rankscore: None
    MetaLR_pred: None
    Reliability_index: None
    MetaRNN_score: None
    MetaRNN_rankscore: None
    MetaRNN_pred: None
    M_CAP_score: None = Field(..., alias="M-CAP_score")
    M_CAP_rankscore: None = Field(..., alias="M-CAP_rankscore")
    M_CAP_pred: None = Field(..., alias="M-CAP_pred")
    REVEL_score: None
    REVEL_rankscore: None
    MutPred_score: str
    MutPred_rankscore: None
    MutPred_protID: str
    MutPred_AAchange: str
    MutPred_Top5features: str
    MVP_score: None
    MVP_rankscore: None
    gMVP_score: None
    gMVP_rankscore: None
    MPC_score: None
    MPC_rankscore: None
    PrimateAI_score: None
    PrimateAI_rankscore: None
    PrimateAI_pred: None
    DEOGEN2_score: None
    DEOGEN2_rankscore: None
    DEOGEN2_pred: None
    BayesDel_addAF_score: float
    BayesDel_addAF_rankscore: float
    BayesDel_addAF_pred: str
    BayesDel_noAF_score: float
    BayesDel_noAF_rankscore: float
    BayesDel_noAF_pred: str
    ClinPred_score: None
    ClinPred_rankscore: None
    ClinPred_pred: None
    LIST_S2_score: None = Field(..., alias="LIST-S2_score")
    LIST_S2_rankscore: None = Field(..., alias="LIST-S2_rankscore")
    LIST_S2_pred: None = Field(..., alias="LIST-S2_pred")
    VARITY_R_score: None
    VARITY_R_rankscore: None
    VARITY_ER_score: None
    VARITY_ER_rankscore: None
    VARITY_R_LOO_score: None
    VARITY_R_LOO_rankscore: None
    VARITY_ER_LOO_score: None
    VARITY_ER_LOO_rankscore: None
    ESM1b_score: None
    ESM1b_rankscore: None
    ESM1b_pred: None
    EVE_score: None
    EVE_rankscore: None
    EVE_Class10_pred: None
    EVE_Class20_pred: None
    EVE_Class25_pred: None
    EVE_Class30_pred: None
    EVE_Class40_pred: None
    EVE_Class50_pred: None
    EVE_Class60_pred: None
    EVE_Class70_pred: None
    EVE_Class75_pred: None
    EVE_Class80_pred: None
    EVE_Class90_pred: None
    AlphaMissense_score: None
    AlphaMissense_rankscore: None
    AlphaMissense_pred: None
    Aloft_Fraction_transcripts_affected: str
    Aloft_prob_Tolerant: str
    Aloft_prob_Recessive: str
    Aloft_prob_Dominant: str
    Aloft_pred: str
    Aloft_Confidence: str
    CADD_raw: float
    CADD_raw_rankscore: float
    CADD_phred: float
    CADD_raw_hg19: float
    CADD_raw_rankscore_hg19: float
    CADD_phred_hg19: float
    DANN_score: float
    DANN_rankscore: float
    fathmm_MKL_coding_score: float = Field(..., alias="fathmm-MKL_coding_score")
    fathmm_MKL_coding_rankscore: float = Field(..., alias="fathmm-MKL_coding_rankscore")
    fathmm_MKL_coding_pred: str = Field(..., alias="fathmm-MKL_coding_pred")
    fathmm_MKL_coding_group: str = Field(..., alias="fathmm-MKL_coding_group")
    fathmm_XF_coding_score: None = Field(..., alias="fathmm-XF_coding_score")
    fathmm_XF_coding_rankscore: None = Field(..., alias="fathmm-XF_coding_rankscore")
    fathmm_XF_coding_pred: None = Field(..., alias="fathmm-XF_coding_pred")
    Eigen_raw_coding: float = Field(..., alias="Eigen-raw_coding")
    Eigen_raw_coding_rankscore: float = Field(..., alias="Eigen-raw_coding_rankscore")
    Eigen_phred_coding: float = Field(..., alias="Eigen-phred_coding")
    Eigen_PC_raw_coding: float = Field(..., alias="Eigen-PC-raw_coding")
    Eigen_PC_raw_coding_rankscore: float = Field(..., alias="Eigen-PC-raw_coding_rankscore")
    Eigen_PC_phred_coding: float = Field(..., alias="Eigen-PC-phred_coding")
    GenoCanyon_score: float
    GenoCanyon_rankscore: float
    integrated_fitCons_score: float
    integrated_fitCons_rankscore: float
    integrated_confidence_value: int
    GM12878_fitCons_score: float
    GM12878_fitCons_rankscore: float
    GM12878_confidence_value: int
    H1_hESC_fitCons_score: float = Field(..., alias="H1-hESC_fitCons_score")
    H1_hESC_fitCons_rankscore: float = Field(..., alias="H1-hESC_fitCons_rankscore")
    H1_hESC_confidence_value: int = Field(..., alias="H1-hESC_confidence_value")
    HUVEC_fitCons_score: float
    HUVEC_fitCons_rankscore: float
    HUVEC_confidence_value: int
    LINSIGHT: float
    LINSIGHT_rankscore: float
    GERP___NR: float = Field(..., alias="GERP++_NR")
    GERP___RS: float = Field(..., alias="GERP++_RS")
    GERP___RS_rankscore: float = Field(..., alias="GERP++_RS_rankscore")
    phyloP100way_vertebrate: float
    phyloP100way_vertebrate_rankscore: float
    phyloP470way_mammalian: float
    phyloP470way_mammalian_rankscore: float
    phyloP17way_primate: float
    phyloP17way_primate_rankscore: float
    phastCons100way_vertebrate: int
    phastCons100way_vertebrate_rankscore: float
    phastCons470way_mammalian: int
    phastCons470way_mammalian_rankscore: float
    phastCons17way_primate: float
    phastCons17way_primate_rankscore: float
    SiPhy_29way_pi: str
    SiPhy_29way_logOdds: float
    SiPhy_29way_logOdds_rankscore: float
    bStatistic: int
    bStatistic_converted_rankscore: float
    field_1000Gp3_AC: None = Field(..., alias="1000Gp3_AC")
    field_1000Gp3_AF: None = Field(..., alias="1000Gp3_AF")
    field_1000Gp3_AFR_AC: None = Field(..., alias="1000Gp3_AFR_AC")
    field_1000Gp3_AFR_AF: None = Field(..., alias="1000Gp3_AFR_AF")
    field_1000Gp3_EUR_AC: None = Field(..., alias="1000Gp3_EUR_AC")
    field_1000Gp3_EUR_AF: None = Field(..., alias="1000Gp3_EUR_AF")
    field_1000Gp3_AMR_AC: None = Field(..., alias="1000Gp3_AMR_AC")
    field_1000Gp3_AMR_AF: None = Field(..., alias="1000Gp3_AMR_AF")
    field_1000Gp3_EAS_AC: None = Field(..., alias="1000Gp3_EAS_AC")
    field_1000Gp3_EAS_AF: None = Field(..., alias="1000Gp3_EAS_AF")
    field_1000Gp3_SAS_AC: None = Field(..., alias="1000Gp3_SAS_AC")
    field_1000Gp3_SAS_AF: None = Field(..., alias="1000Gp3_SAS_AF")
    TWINSUK_AC: None
    TWINSUK_AF: None
    ALSPAC_AC: None
    ALSPAC_AF: None
    UK10K_AC: None
    UK10K_AF: None
    ESP6500_AA_AC: None
    ESP6500_AA_AF: None
    ESP6500_EA_AC: None
    ESP6500_EA_AF: None
    ExAC_AC: None
    ExAC_AF: None
    ExAC_Adj_AC: None
    ExAC_Adj_AF: None
    ExAC_AFR_AC: None
    ExAC_AFR_AF: None
    ExAC_AMR_AC: None
    ExAC_AMR_AF: None
    ExAC_EAS_AC: None
    ExAC_EAS_AF: None
    ExAC_FIN_AC: None
    ExAC_FIN_AF: None
    ExAC_NFE_AC: None
    ExAC_NFE_AF: None
    ExAC_SAS_AC: None
    ExAC_SAS_AF: None
    ExAC_nonTCGA_AC: None
    ExAC_nonTCGA_AF: None
    ExAC_nonTCGA_Adj_AC: None
    ExAC_nonTCGA_Adj_AF: None
    ExAC_nonTCGA_AFR_AC: None
    ExAC_nonTCGA_AFR_AF: None
    ExAC_nonTCGA_AMR_AC: None
    ExAC_nonTCGA_AMR_AF: None
    ExAC_nonTCGA_EAS_AC: None
    ExAC_nonTCGA_EAS_AF: None
    ExAC_nonTCGA_FIN_AC: None
    ExAC_nonTCGA_FIN_AF: None
    ExAC_nonTCGA_NFE_AC: None
    ExAC_nonTCGA_NFE_AF: None
    ExAC_nonTCGA_SAS_AC: None
    ExAC_nonTCGA_SAS_AF: None
    ExAC_nonpsych_AC: None
    ExAC_nonpsych_AF: None
    ExAC_nonpsych_Adj_AC: None
    ExAC_nonpsych_Adj_AF: None
    ExAC_nonpsych_AFR_AC: None
    ExAC_nonpsych_AFR_AF: None
    ExAC_nonpsych_AMR_AC: None
    ExAC_nonpsych_AMR_AF: None
    ExAC_nonpsych_EAS_AC: None
    ExAC_nonpsych_EAS_AF: None
    ExAC_nonpsych_FIN_AC: None
    ExAC_nonpsych_FIN_AF: None
    ExAC_nonpsych_NFE_AC: None
    ExAC_nonpsych_NFE_AF: None
    ExAC_nonpsych_SAS_AC: None
    ExAC_nonpsych_SAS_AF: None
    gnomAD_exomes_flag: None
    gnomAD_exomes_AC: None
    gnomAD_exomes_AN: None
    gnomAD_exomes_AF: None
    gnomAD_exomes_nhomalt: None
    gnomAD_exomes_AFR_AC: None
    gnomAD_exomes_AFR_AN: None
    gnomAD_exomes_AFR_AF: None
    gnomAD_exomes_AFR_nhomalt: None
    gnomAD_exomes_AMR_AC: None
    gnomAD_exomes_AMR_AN: None
    gnomAD_exomes_AMR_AF: None
    gnomAD_exomes_AMR_nhomalt: None
    gnomAD_exomes_ASJ_AC: None
    gnomAD_exomes_ASJ_AN: None
    gnomAD_exomes_ASJ_AF: None
    gnomAD_exomes_ASJ_nhomalt: None
    gnomAD_exomes_EAS_AC: None
    gnomAD_exomes_EAS_AN: None
    gnomAD_exomes_EAS_AF: None
    gnomAD_exomes_EAS_nhomalt: None
    gnomAD_exomes_FIN_AC: None
    gnomAD_exomes_FIN_AN: None
    gnomAD_exomes_FIN_AF: None
    gnomAD_exomes_FIN_nhomalt: None
    gnomAD_exomes_NFE_AC: None
    gnomAD_exomes_NFE_AN: None
    gnomAD_exomes_NFE_AF: None
    gnomAD_exomes_NFE_nhomalt: None
    gnomAD_exomes_SAS_AC: None
    gnomAD_exomes_SAS_AN: None
    gnomAD_exomes_SAS_AF: None
    gnomAD_exomes_SAS_nhomalt: None
    gnomAD_exomes_POPMAX_AC: None
    gnomAD_exomes_POPMAX_AN: None
    gnomAD_exomes_POPMAX_AF: None
    gnomAD_exomes_POPMAX_nhomalt: None
    gnomAD_exomes_controls_AC: None
    gnomAD_exomes_controls_AN: None
    gnomAD_exomes_controls_AF: None
    gnomAD_exomes_controls_nhomalt: None
    gnomAD_exomes_non_neuro_AC: None
    gnomAD_exomes_non_neuro_AN: None
    gnomAD_exomes_non_neuro_AF: None
    gnomAD_exomes_non_neuro_nhomalt: None
    gnomAD_exomes_non_cancer_AC: None
    gnomAD_exomes_non_cancer_AN: None
    gnomAD_exomes_non_cancer_AF: None
    gnomAD_exomes_non_cancer_nhomalt: None
    gnomAD_exomes_non_topmed_AC: None
    gnomAD_exomes_non_topmed_AN: None
    gnomAD_exomes_non_topmed_AF: None
    gnomAD_exomes_non_topmed_nhomalt: None
    gnomAD_exomes_controls_AFR_AC: None
    gnomAD_exomes_controls_AFR_AN: None
    gnomAD_exomes_controls_AFR_AF: None
    gnomAD_exomes_controls_AFR_nhomalt: None
    gnomAD_exomes_controls_AMR_AC: None
    gnomAD_exomes_controls_AMR_AN: None
    gnomAD_exomes_controls_AMR_AF: None
    gnomAD_exomes_controls_AMR_nhomalt: None
    gnomAD_exomes_controls_ASJ_AC: None
    gnomAD_exomes_controls_ASJ_AN: None
    gnomAD_exomes_controls_ASJ_AF: None
    gnomAD_exomes_controls_ASJ_nhomalt: None
    gnomAD_exomes_controls_EAS_AC: None
    gnomAD_exomes_controls_EAS_AN: None
    gnomAD_exomes_controls_EAS_AF: None
    gnomAD_exomes_controls_EAS_nhomalt: None
    gnomAD_exomes_controls_FIN_AC: None
    gnomAD_exomes_controls_FIN_AN: None
    gnomAD_exomes_controls_FIN_AF: None
    gnomAD_exomes_controls_FIN_nhomalt: None
    gnomAD_exomes_controls_NFE_AC: None
    gnomAD_exomes_controls_NFE_AN: None
    gnomAD_exomes_controls_NFE_AF: None
    gnomAD_exomes_controls_NFE_nhomalt: None
    gnomAD_exomes_controls_SAS_AC: None
    gnomAD_exomes_controls_SAS_AN: None
    gnomAD_exomes_controls_SAS_AF: None
    gnomAD_exomes_controls_SAS_nhomalt: None
    gnomAD_exomes_controls_POPMAX_AC: None
    gnomAD_exomes_controls_POPMAX_AN: None
    gnomAD_exomes_controls_POPMAX_AF: None
    gnomAD_exomes_controls_POPMAX_nhomalt: None
    gnomAD_exomes_non_neuro_AFR_AC: None
    gnomAD_exomes_non_neuro_AFR_AN: None
    gnomAD_exomes_non_neuro_AFR_AF: None
    gnomAD_exomes_non_neuro_AFR_nhomalt: None
    gnomAD_exomes_non_neuro_AMR_AC: None
    gnomAD_exomes_non_neuro_AMR_AN: None
    gnomAD_exomes_non_neuro_AMR_AF: None
    gnomAD_exomes_non_neuro_AMR_nhomalt: None
    gnomAD_exomes_non_neuro_ASJ_AC: None
    gnomAD_exomes_non_neuro_ASJ_AN: None
    gnomAD_exomes_non_neuro_ASJ_AF: None
    gnomAD_exomes_non_neuro_ASJ_nhomalt: None
    gnomAD_exomes_non_neuro_EAS_AC: None
    gnomAD_exomes_non_neuro_EAS_AN: None
    gnomAD_exomes_non_neuro_EAS_AF: None
    gnomAD_exomes_non_neuro_EAS_nhomalt: None
    gnomAD_exomes_non_neuro_FIN_AC: None
    gnomAD_exomes_non_neuro_FIN_AN: None
    gnomAD_exomes_non_neuro_FIN_AF: None
    gnomAD_exomes_non_neuro_FIN_nhomalt: None
    gnomAD_exomes_non_neuro_NFE_AC: None
    gnomAD_exomes_non_neuro_NFE_AN: None
    gnomAD_exomes_non_neuro_NFE_AF: None
    gnomAD_exomes_non_neuro_NFE_nhomalt: None
    gnomAD_exomes_non_neuro_SAS_AC: None
    gnomAD_exomes_non_neuro_SAS_AN: None
    gnomAD_exomes_non_neuro_SAS_AF: None
    gnomAD_exomes_non_neuro_SAS_nhomalt: None
    gnomAD_exomes_non_neuro_POPMAX_AC: None
    gnomAD_exomes_non_neuro_POPMAX_AN: None
    gnomAD_exomes_non_neuro_POPMAX_AF: None
    gnomAD_exomes_non_neuro_POPMAX_nhomalt: None
    gnomAD_exomes_non_cancer_AFR_AC: None
    gnomAD_exomes_non_cancer_AFR_AN: None
    gnomAD_exomes_non_cancer_AFR_AF: None
    gnomAD_exomes_non_cancer_AFR_nhomalt: None
    gnomAD_exomes_non_cancer_AMR_AC: None
    gnomAD_exomes_non_cancer_AMR_AN: None
    gnomAD_exomes_non_cancer_AMR_AF: None
    gnomAD_exomes_non_cancer_AMR_nhomalt: None
    gnomAD_exomes_non_cancer_ASJ_AC: None
    gnomAD_exomes_non_cancer_ASJ_AN: None
    gnomAD_exomes_non_cancer_ASJ_AF: None
    gnomAD_exomes_non_cancer_ASJ_nhomalt: None
    gnomAD_exomes_non_cancer_EAS_AC: None
    gnomAD_exomes_non_cancer_EAS_AN: None
    gnomAD_exomes_non_cancer_EAS_AF: None
    gnomAD_exomes_non_cancer_EAS_nhomalt: None
    gnomAD_exomes_non_cancer_FIN_AC: None
    gnomAD_exomes_non_cancer_FIN_AN: None
    gnomAD_exomes_non_cancer_FIN_AF: None
    gnomAD_exomes_non_cancer_FIN_nhomalt: None
    gnomAD_exomes_non_cancer_NFE_AC: None
    gnomAD_exomes_non_cancer_NFE_AN: None
    gnomAD_exomes_non_cancer_NFE_AF: None
    gnomAD_exomes_non_cancer_NFE_nhomalt: None
    gnomAD_exomes_non_cancer_SAS_AC: None
    gnomAD_exomes_non_cancer_SAS_AN: None
    gnomAD_exomes_non_cancer_SAS_AF: None
    gnomAD_exomes_non_cancer_SAS_nhomalt: None
    gnomAD_exomes_non_cancer_POPMAX_AC: None
    gnomAD_exomes_non_cancer_POPMAX_AN: None
    gnomAD_exomes_non_cancer_POPMAX_AF: None
    gnomAD_exomes_non_cancer_POPMAX_nhomalt: None
    gnomAD_exomes_non_topmed_AFR_AC: None
    gnomAD_exomes_non_topmed_AFR_AN: None
    gnomAD_exomes_non_topmed_AFR_AF: None
    gnomAD_exomes_non_topmed_AFR_nhomalt: None
    gnomAD_exomes_non_topmed_AMR_AC: None
    gnomAD_exomes_non_topmed_AMR_AN: None
    gnomAD_exomes_non_topmed_AMR_AF: None
    gnomAD_exomes_non_topmed_AMR_nhomalt: None
    gnomAD_exomes_non_topmed_ASJ_AC: None
    gnomAD_exomes_non_topmed_ASJ_AN: None
    gnomAD_exomes_non_topmed_ASJ_AF: None
    gnomAD_exomes_non_topmed_ASJ_nhomalt: None
    gnomAD_exomes_non_topmed_EAS_AC: None
    gnomAD_exomes_non_topmed_EAS_AN: None
    gnomAD_exomes_non_topmed_EAS_AF: None
    gnomAD_exomes_non_topmed_EAS_nhomalt: None
    gnomAD_exomes_non_topmed_FIN_AC: None
    gnomAD_exomes_non_topmed_FIN_AN: None
    gnomAD_exomes_non_topmed_FIN_AF: None
    gnomAD_exomes_non_topmed_FIN_nhomalt: None
    gnomAD_exomes_non_topmed_NFE_AC: None
    gnomAD_exomes_non_topmed_NFE_AN: None
    gnomAD_exomes_non_topmed_NFE_AF: None
    gnomAD_exomes_non_topmed_NFE_nhomalt: None
    gnomAD_exomes_non_topmed_SAS_AC: None
    gnomAD_exomes_non_topmed_SAS_AN: None
    gnomAD_exomes_non_topmed_SAS_AF: None
    gnomAD_exomes_non_topmed_SAS_nhomalt: None
    gnomAD_exomes_non_topmed_POPMAX_AC: None
    gnomAD_exomes_non_topmed_POPMAX_AN: None
    gnomAD_exomes_non_topmed_POPMAX_AF: None
    gnomAD_exomes_non_topmed_POPMAX_nhomalt: None
    gnomAD_genomes_flag: None
    gnomAD_genomes_AC: None
    gnomAD_genomes_AN: None
    gnomAD_genomes_AF: None
    gnomAD_genomes_nhomalt: None
    gnomAD_genomes_POPMAX_AC: None
    gnomAD_genomes_POPMAX_AN: None
    gnomAD_genomes_POPMAX_AF: None
    gnomAD_genomes_POPMAX_nhomalt: None
    gnomAD_genomes_AFR_AC: None
    gnomAD_genomes_AFR_AN: None
    gnomAD_genomes_AFR_AF: None
    gnomAD_genomes_AFR_nhomalt: None
    gnomAD_genomes_AMI_AC: None
    gnomAD_genomes_AMI_AN: None
    gnomAD_genomes_AMI_AF: None
    gnomAD_genomes_AMI_nhomalt: None
    gnomAD_genomes_AMR_AC: None
    gnomAD_genomes_AMR_AN: None
    gnomAD_genomes_AMR_AF: None
    gnomAD_genomes_AMR_nhomalt: None
    gnomAD_genomes_ASJ_AC: None
    gnomAD_genomes_ASJ_AN: None
    gnomAD_genomes_ASJ_AF: None
    gnomAD_genomes_ASJ_nhomalt: None
    gnomAD_genomes_EAS_AC: None
    gnomAD_genomes_EAS_AN: None
    gnomAD_genomes_EAS_AF: None
    gnomAD_genomes_EAS_nhomalt: None
    gnomAD_genomes_FIN_AC: None
    gnomAD_genomes_FIN_AN: None
    gnomAD_genomes_FIN_AF: None
    gnomAD_genomes_FIN_nhomalt: None
    gnomAD_genomes_MID_AC: None
    gnomAD_genomes_MID_AN: None
    gnomAD_genomes_MID_AF: None
    gnomAD_genomes_MID_nhomalt: None
    gnomAD_genomes_NFE_AC: None
    gnomAD_genomes_NFE_AN: None
    gnomAD_genomes_NFE_AF: None
    gnomAD_genomes_NFE_nhomalt: None
    gnomAD_genomes_SAS_AC: None
    gnomAD_genomes_SAS_AN: None
    gnomAD_genomes_SAS_AF: None
    gnomAD_genomes_SAS_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_AC: None
    gnomAD_genomes_controls_and_biobanks_AN: None
    gnomAD_genomes_controls_and_biobanks_AF: None
    gnomAD_genomes_controls_and_biobanks_nhomalt: None
    gnomAD_genomes_non_neuro_AC: None
    gnomAD_genomes_non_neuro_AN: None
    gnomAD_genomes_non_neuro_AF: None
    gnomAD_genomes_non_neuro_nhomalt: None
    gnomAD_genomes_non_cancer_AC: None
    gnomAD_genomes_non_cancer_AN: None
    gnomAD_genomes_non_cancer_AF: None
    gnomAD_genomes_non_cancer_nhomalt: None
    gnomAD_genomes_non_topmed_AC: None
    gnomAD_genomes_non_topmed_AN: None
    gnomAD_genomes_non_topmed_AF: None
    gnomAD_genomes_non_topmed_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_AFR_AC: None
    gnomAD_genomes_controls_and_biobanks_AFR_AN: None
    gnomAD_genomes_controls_and_biobanks_AFR_AF: None
    gnomAD_genomes_controls_and_biobanks_AFR_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_AMI_AC: None
    gnomAD_genomes_controls_and_biobanks_AMI_AN: None
    gnomAD_genomes_controls_and_biobanks_AMI_AF: None
    gnomAD_genomes_controls_and_biobanks_AMI_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_AMR_AC: None
    gnomAD_genomes_controls_and_biobanks_AMR_AN: None
    gnomAD_genomes_controls_and_biobanks_AMR_AF: None
    gnomAD_genomes_controls_and_biobanks_AMR_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_ASJ_AC: None
    gnomAD_genomes_controls_and_biobanks_ASJ_AN: None
    gnomAD_genomes_controls_and_biobanks_ASJ_AF: None
    gnomAD_genomes_controls_and_biobanks_ASJ_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_EAS_AC: None
    gnomAD_genomes_controls_and_biobanks_EAS_AN: None
    gnomAD_genomes_controls_and_biobanks_EAS_AF: None
    gnomAD_genomes_controls_and_biobanks_EAS_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_FIN_AC: None
    gnomAD_genomes_controls_and_biobanks_FIN_AN: None
    gnomAD_genomes_controls_and_biobanks_FIN_AF: None
    gnomAD_genomes_controls_and_biobanks_FIN_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_MID_AC: None
    gnomAD_genomes_controls_and_biobanks_MID_AN: None
    gnomAD_genomes_controls_and_biobanks_MID_AF: None
    gnomAD_genomes_controls_and_biobanks_MID_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_NFE_AC: None
    gnomAD_genomes_controls_and_biobanks_NFE_AN: None
    gnomAD_genomes_controls_and_biobanks_NFE_AF: None
    gnomAD_genomes_controls_and_biobanks_NFE_nhomalt: None
    gnomAD_genomes_controls_and_biobanks_SAS_AC: None
    gnomAD_genomes_controls_and_biobanks_SAS_AN: None
    gnomAD_genomes_controls_and_biobanks_SAS_AF: None
    gnomAD_genomes_controls_and_biobanks_SAS_nhomalt: None
    gnomAD_genomes_non_neuro_AFR_AC: None
    gnomAD_genomes_non_neuro_AFR_AN: None
    gnomAD_genomes_non_neuro_AFR_AF: None
    gnomAD_genomes_non_neuro_AFR_nhomalt: None
    gnomAD_genomes_non_neuro_AMI_AC: None
    gnomAD_genomes_non_neuro_AMI_AN: None
    gnomAD_genomes_non_neuro_AMI_AF: None
    gnomAD_genomes_non_neuro_AMI_nhomalt: None
    gnomAD_genomes_non_neuro_AMR_AC: None
    gnomAD_genomes_non_neuro_AMR_AN: None
    gnomAD_genomes_non_neuro_AMR_AF: None
    gnomAD_genomes_non_neuro_AMR_nhomalt: None
    gnomAD_genomes_non_neuro_ASJ_AC: None
    gnomAD_genomes_non_neuro_ASJ_AN: None
    gnomAD_genomes_non_neuro_ASJ_AF: None
    gnomAD_genomes_non_neuro_ASJ_nhomalt: None
    gnomAD_genomes_non_neuro_EAS_AC: None
    gnomAD_genomes_non_neuro_EAS_AN: None
    gnomAD_genomes_non_neuro_EAS_AF: None
    gnomAD_genomes_non_neuro_EAS_nhomalt: None
    gnomAD_genomes_non_neuro_FIN_AC: None
    gnomAD_genomes_non_neuro_FIN_AN: None
    gnomAD_genomes_non_neuro_FIN_AF: None
    gnomAD_genomes_non_neuro_FIN_nhomalt: None
    gnomAD_genomes_non_neuro_MID_AC: None
    gnomAD_genomes_non_neuro_MID_AN: None
    gnomAD_genomes_non_neuro_MID_AF: None
    gnomAD_genomes_non_neuro_MID_nhomalt: None
    gnomAD_genomes_non_neuro_NFE_AC: None
    gnomAD_genomes_non_neuro_NFE_AN: None
    gnomAD_genomes_non_neuro_NFE_AF: None
    gnomAD_genomes_non_neuro_NFE_nhomalt: None
    gnomAD_genomes_non_neuro_SAS_AC: None
    gnomAD_genomes_non_neuro_SAS_AN: None
    gnomAD_genomes_non_neuro_SAS_AF: None
    gnomAD_genomes_non_neuro_SAS_nhomalt: None
    gnomAD_genomes_non_cancer_AFR_AC: None
    gnomAD_genomes_non_cancer_AFR_AN: None
    gnomAD_genomes_non_cancer_AFR_AF: None
    gnomAD_genomes_non_cancer_AFR_nhomalt: None
    gnomAD_genomes_non_cancer_AMI_AC: None
    gnomAD_genomes_non_cancer_AMI_AN: None
    gnomAD_genomes_non_cancer_AMI_AF: None
    gnomAD_genomes_non_cancer_AMI_nhomalt: None
    gnomAD_genomes_non_cancer_AMR_AC: None
    gnomAD_genomes_non_cancer_AMR_AN: None
    gnomAD_genomes_non_cancer_AMR_AF: None
    gnomAD_genomes_non_cancer_AMR_nhomalt: None
    gnomAD_genomes_non_cancer_ASJ_AC: None
    gnomAD_genomes_non_cancer_ASJ_AN: None
    gnomAD_genomes_non_cancer_ASJ_AF: None
    gnomAD_genomes_non_cancer_ASJ_nhomalt: None
    gnomAD_genomes_non_cancer_EAS_AC: None
    gnomAD_genomes_non_cancer_EAS_AN: None
    gnomAD_genomes_non_cancer_EAS_AF: None
    gnomAD_genomes_non_cancer_EAS_nhomalt: None
    gnomAD_genomes_non_cancer_FIN_AC: None
    gnomAD_genomes_non_cancer_FIN_AN: None
    gnomAD_genomes_non_cancer_FIN_AF: None
    gnomAD_genomes_non_cancer_FIN_nhomalt: None
    gnomAD_genomes_non_cancer_MID_AC: None
    gnomAD_genomes_non_cancer_MID_AN: None
    gnomAD_genomes_non_cancer_MID_AF: None
    gnomAD_genomes_non_cancer_MID_nhomalt: None
    gnomAD_genomes_non_cancer_NFE_AC: None
    gnomAD_genomes_non_cancer_NFE_AN: None
    gnomAD_genomes_non_cancer_NFE_AF: None
    gnomAD_genomes_non_cancer_NFE_nhomalt: None
    gnomAD_genomes_non_cancer_SAS_AC: None
    gnomAD_genomes_non_cancer_SAS_AN: None
    gnomAD_genomes_non_cancer_SAS_AF: None
    gnomAD_genomes_non_cancer_SAS_nhomalt: None
    gnomAD_genomes_non_topmed_AFR_AC: None
    gnomAD_genomes_non_topmed_AFR_AN: None
    gnomAD_genomes_non_topmed_AFR_AF: None
    gnomAD_genomes_non_topmed_AFR_nhomalt: None
    gnomAD_genomes_non_topmed_AMI_AC: None
    gnomAD_genomes_non_topmed_AMI_AN: None
    gnomAD_genomes_non_topmed_AMI_AF: None
    gnomAD_genomes_non_topmed_AMI_nhomalt: None
    gnomAD_genomes_non_topmed_AMR_AC: None
    gnomAD_genomes_non_topmed_AMR_AN: None
    gnomAD_genomes_non_topmed_AMR_AF: None
    gnomAD_genomes_non_topmed_AMR_nhomalt: None
    gnomAD_genomes_non_topmed_ASJ_AC: None
    gnomAD_genomes_non_topmed_ASJ_AN: None
    gnomAD_genomes_non_topmed_ASJ_AF: None
    gnomAD_genomes_non_topmed_ASJ_nhomalt: None
    gnomAD_genomes_non_topmed_EAS_AC: None
    gnomAD_genomes_non_topmed_EAS_AN: None
    gnomAD_genomes_non_topmed_EAS_AF: None
    gnomAD_genomes_non_topmed_EAS_nhomalt: None
    gnomAD_genomes_non_topmed_FIN_AC: None
    gnomAD_genomes_non_topmed_FIN_AN: None
    gnomAD_genomes_non_topmed_FIN_AF: None
    gnomAD_genomes_non_topmed_FIN_nhomalt: None
    gnomAD_genomes_non_topmed_MID_AC: None
    gnomAD_genomes_non_topmed_MID_AN: None
    gnomAD_genomes_non_topmed_MID_AF: None
    gnomAD_genomes_non_topmed_MID_nhomalt: None
    gnomAD_genomes_non_topmed_NFE_AC: None
    gnomAD_genomes_non_topmed_NFE_AN: None
    gnomAD_genomes_non_topmed_NFE_AF: None
    gnomAD_genomes_non_topmed_NFE_nhomalt: None
    gnomAD_genomes_non_topmed_SAS_AC: None
    gnomAD_genomes_non_topmed_SAS_AN: None
    gnomAD_genomes_non_topmed_SAS_AF: None
    gnomAD_genomes_non_topmed_SAS_nhomalt: None
    ALFA_European_AC: None
    ALFA_European_AN: None
    ALFA_European_AF: None
    ALFA_African_Others_AC: None
    ALFA_African_Others_AN: None
    ALFA_African_Others_AF: None
    ALFA_East_Asian_AC: None
    ALFA_East_Asian_AN: None
    ALFA_East_Asian_AF: None
    ALFA_African_American_AC: None
    ALFA_African_American_AN: None
    ALFA_African_American_AF: None
    ALFA_Latin_American_1_AC: None
    ALFA_Latin_American_1_AN: None
    ALFA_Latin_American_1_AF: None
    ALFA_Latin_American_2_AC: None
    ALFA_Latin_American_2_AN: None
    ALFA_Latin_American_2_AF: None
    ALFA_Other_Asian_AC: None
    ALFA_Other_Asian_AN: None
    ALFA_Other_Asian_AF: None
    ALFA_South_Asian_AC: None
    ALFA_South_Asian_AN: None
    ALFA_South_Asian_AF: None
    ALFA_Other_AC: None
    ALFA_Other_AN: None
    ALFA_Other_AF: None
    ALFA_African_AC: None
    ALFA_African_AN: None
    ALFA_African_AF: None
    ALFA_Asian_AC: None
    ALFA_Asian_AN: None
    ALFA_Asian_AF: None
    ALFA_Total_AC: None
    ALFA_Total_AN: None
    ALFA_Total_AF: None
    clinvar_id: None
    clinvar_clnsig: None
    clinvar_trait: None
    clinvar_review: None
    clinvar_hgvs: None
    clinvar_var_source: None
    clinvar_MedGen_id: None
    clinvar_OMIM_id: None
    clinvar_Orphanet_id: None
    Interpro_domain: None
    GTEx_V8_gene: None
    GTEx_V8_tissue: None
    Geuvadis_eQTL_target_gene: None


class Polyphen(BaseModel):
    prediction: str
    score: Optional[float] = None


class Sift(BaseModel):
    prediction: str
    score: Optional[float] = None


class Domain(BaseModel):
    id: str
    source: str


class VepItem(BaseModel):
    allele: str
    consequence: str
    impact: str
    symbol: str
    gene: str
    featureType: str
    feature: str
    featureBiotype: str
    exon: Optional[str] = None
    hgvsc: Optional[str] = None
    cdnaPosition: Optional[str] = None
    dbsnpId: str
    strand: str
    variantClass: str
    minimised: str
    symbolSource: str
    hgncId: str
    canonical: Optional[bool] = None
    ccds: Optional[str] = None
    ensp: Optional[str] = None
    swissprot: Optional[str] = None
    trembl: Optional[str] = None
    uniparc: Optional[str] = None
    genePheno: str
    intron: Optional[str] = None
    flags: Optional[str] = None
    existingVariation: Optional[str] = None
    afrMaf: Optional[float] = None
    exacAdjMaf: Optional[float] = None
    exacAfrMaf: Optional[float] = None
    exacAmrMaf: Optional[float] = None
    exacEasMaf: Optional[float] = None
    exacFinMaf: Optional[float] = None
    exacNfeMaf: Optional[float] = None
    exacOthMaf: Optional[float] = None
    exacSasMaf: Optional[float] = None
    hgvsp: Optional[str] = None
    cdsPosition: Optional[str] = None
    proteinPosition: Optional[str] = None
    aminoAcids: Optional[str] = None
    codons: Optional[str] = None
    gmaf: Optional[float] = None
    amrMaf: Optional[float] = None
    easMaf: Optional[int] = None
    eurMaf: Optional[float] = None
    sasMaf: Optional[float] = None
    aaMaf: Optional[float] = None
    polyphen: Optional[Polyphen] = None
    sift: Optional[Sift] = None
    domains: Optional[List[Domain]] = None
    distance: Optional[str] = None
    eaMaf: Optional[float] = None
    exacMaf: Optional[float] = None
    clinSig: Optional[str] = None
    pheno: Optional[str] = None
    lof: Optional[str] = None
    lofInfo: Optional[str] = None
    somatic: Optional[str] = None


class Overall(BaseModel):
    an: int
    ac: Optional[int] = None
    af: Optional[float] = None
    nhomalt: Optional[int] = None


class Xx(BaseModel):
    an: int
    ac: Optional[int] = None
    af: Optional[float] = None
    nhomalt: Optional[int] = None


class Xy(BaseModel):
    an: int
    ac: Optional[int] = None
    af: Optional[float] = None


class Counts(BaseModel):
    overall: Optional[Overall] = None
    xx: Optional[Xx] = None
    xy: Optional[Xy] = None


class ByPopulationItem(BaseModel):
    population: str
    counts: Counts
    faf95: Optional[float] = None
    faf99: Optional[float] = None


class Overall1(BaseModel):
    ac: Optional[int] = None
    an: int
    af: Optional[float] = None
    nhomalt: Optional[int] = None


class Xy1(BaseModel):
    ac: Optional[int] = None
    an: int
    af: Optional[float] = None


class BySex(BaseModel):
    overall: Overall1
    xx: Xx
    xy: Xy1


class Raw(BaseModel):
    ac: Optional[int] = None
    an: int
    af: Optional[float] = None
    nhomalt: Optional[int] = None


class AlleleCount(BaseModel):
    byPopulation: List[ByPopulationItem]
    bySex: BySex
    raw: Raw
    popmax: Optional[str] = None
    afPopmax: Optional[float] = None
    acPopmax: Optional[int] = None
    anPopmax: Optional[int] = None
    nhomaltPopmax: Optional[int] = None
    cohort: Optional[str] = None


class VariantInfo(BaseModel):
    variantType: str
    alleleType: str
    nAltAlleles: int
    hasStar: Optional[bool] = None
    wasMixed: Optional[bool] = None


class QualityInfo(BaseModel):
    fs: float
    inbreedingCoeff: float
    mq: float
    mqRankSum: float
    qd: float
    readPosRankSum: float
    baseQRankSum: float
    clippingRankSum: float
    sor: float
    dp: int
    vqslod: float
    vqsrCulprit: str
    pabMax: float
    vqsrNegativeTrainSite: Optional[bool] = None
    vqsrPositiveTrainSite: Optional[bool] = None
    lcr: Optional[bool] = None


class AgeInfo(BaseModel):
    ageHistHomNSmaller: int
    ageHistHomNLarger: int
    ageHistHetNSmaller: int
    ageHistHetNLarger: int


class GnomadExome(BaseModel):
    chrom: str
    pos: int
    refAllele: str
    altAllele: str
    vep: List[VepItem]
    alleleCounts: List[AlleleCount]
    variantInfo: VariantInfo
    qualityInfo: QualityInfo
    ageInfo: AgeInfo


class Sift1(BaseModel):
    prediction: str
    score: float


class VepItem1(BaseModel):
    allele: str
    consequence: str
    impact: str
    symbol: Optional[str] = None
    gene: Optional[str] = None
    featureType: str
    feature: str
    featureBiotype: Optional[str] = None
    exon: Optional[str] = None
    hgvsc: Optional[str] = None
    cdnaPosition: Optional[str] = None
    existingVariation: Optional[str] = None
    dbsnpId: str
    strand: str
    variantClass: str
    minimised: str
    symbolSource: Optional[str] = None
    hgncId: Optional[str] = None
    canonical: Optional[bool] = None
    ccds: Optional[str] = None
    ensp: Optional[str] = None
    swissprot: Optional[str] = None
    trembl: Optional[str] = None
    uniparc: Optional[str] = None
    genePheno: Optional[str] = None
    gmaf: Optional[float] = None
    amrMaf: Optional[float] = None
    easMaf: Optional[float] = None
    eurMaf: Optional[float] = None
    sasMaf: Optional[float] = None
    aaMaf: Optional[float] = None
    intron: Optional[str] = None
    flags: Optional[str] = None
    afrMaf: Optional[float] = None
    exacAdjMaf: Optional[float] = None
    exacAfrMaf: Optional[float] = None
    exacAmrMaf: Optional[float] = None
    exacEasMaf: Optional[float] = None
    exacFinMaf: Optional[float] = None
    exacNfeMaf: Optional[float] = None
    exacOthMaf: Optional[float] = None
    exacSasMaf: Optional[int] = None
    hgvsp: Optional[str] = None
    cdsPosition: Optional[str] = None
    proteinPosition: Optional[str] = None
    aminoAcids: Optional[str] = None
    codons: Optional[str] = None
    sift: Optional[Sift1] = None
    polyphen: Optional[Polyphen] = None
    motifName: Optional[str] = None
    motifPos: Optional[str] = None
    highInfPos: Optional[str] = None
    motifScoreChange: Optional[str] = None
    pheno: Optional[str] = None
    distance: Optional[str] = None
    domains: Optional[List[Domain]] = None
    eaMaf: Optional[float] = None
    exacMaf: Optional[float] = None
    clinSig: Optional[str] = None


class Xx2(BaseModel):
    ac: Optional[int] = None
    an: int
    af: Optional[float] = None
    nhomalt: Optional[int] = None


class Xy2(BaseModel):
    ac: Optional[int] = None
    an: int
    af: Optional[float] = None
    nhomalt: Optional[int] = None


class Counts1(BaseModel):
    overall: Optional[Overall1] = None
    xx: Optional[Xx2] = None
    xy: Optional[Xy2] = None


class ByPopulationItem1(BaseModel):
    population: str
    counts: Counts1
    faf95: Optional[float] = None
    faf99: Optional[float] = None


class BySex1(BaseModel):
    overall: Optional[Overall1] = None
    xx: Optional[Xx2] = None
    xy: Optional[Xy2] = None


class AlleleCount1(BaseModel):
    byPopulation: List[ByPopulationItem1]
    bySex: BySex1
    raw: Optional[Raw] = None
    popmax: Optional[str] = None
    afPopmax: Optional[float] = None
    acPopmax: Optional[int] = None
    anPopmax: Optional[int] = None
    nhomaltPopmax: Optional[int] = None
    cohort: Optional[str] = None


class GnomadGenome(BaseModel):
    chrom: str
    pos: int
    refAllele: str
    altAllele: str
    vep: List[VepItem1]
    alleleCounts: List[AlleleCount1]
    variantInfo: VariantInfo
    qualityInfo: QualityInfo
    ageInfo: AgeInfo


class Record(BaseModel):
    chrom: str
    start: int
    stop: int
    hgncId: str
    enstId: str
    exonNum: int
    exonCount: int
    alignment: str


class UcscConservationItem(BaseModel):
    records: List[Record]


class Accession(BaseModel):
    accession: str
    version: int


class Description(BaseModel):
    value: str
    dateLastEvaluated: str
    submissionCount: int


class GermlineClassification(BaseModel):
    reviewStatus: str
    description: Description


class Classifications(BaseModel):
    germlineClassification: GermlineClassification


class Rcv(BaseModel):
    accession: Accession
    title: str
    classifications: Classifications


class Explanation(BaseModel):
    value: str
    dataSource: str
    type: str


class Comment(BaseModel):
    value: str
    dataSource: str
    type: str


class GermlineClassification1(BaseModel):
    reviewStatus: str
    description: str
    dateLastEvaluated: str
    dateCreated: str
    mostRecentSubmission: str
    numberOfSubmitters: int
    numberOfSubmissions: int
    explanation: Optional[Explanation] = None
    comments: Optional[List[Comment]] = None


class Classifications1(BaseModel):
    germlineClassification: GermlineClassification1


class SequenceLocation(BaseModel):
    assembly: str
    chr: str
    accession: str
    start: int
    stop: int
    displayStart: int
    displayStop: int
    variantLength: int
    referenceAllele: Optional[str] = None
    alternateAllele: Optional[str] = None
    positionVcf: int
    referenceAlleleVcf: str
    alternateAlleleVcf: str


class Record1(BaseModel):
    accession: Accession
    rcvs: List[Rcv]
    name: str
    variationType: str
    classifications: Classifications1
    sequenceLocation: SequenceLocation
    hgncIds: List[str]


class ClinvarItem(BaseModel):
    records: List[Record1]


class Result(BaseModel):
    cadd: Cadd
    dbsnp: List[DbsnpItem]
    dbnsfp: Dbnsfp
    dbscsnv: Dict[str, Any]
    gnomad_mtdna: List
    gnomad_exomes: List[GnomadExome]
    gnomad_genomes: List[GnomadGenome]
    helixmtdb: List
    ucsc_conservation: List[UcscConservationItem]
    clinvar: List[ClinvarItem]


class Model(BaseModel):
    server_version: str
    query: Query
    result: Result
