# generated by datamodel-codegen:
#   filename:  BRCA1_gene.json
#   timestamp: 2024-06-25T13:17:09+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, validator


class Clingen(BaseModel):
    geneSymbol: Optional[str] = None
    ncbiGeneId: Optional[str] = None
    genomicLocation37: Optional[str] = None
    genomicLocation38: Optional[str] = None
    haploinsufficiencyScore: Optional[str] = None
    triplosensitivityScore: Optional[str] = None
    haploinsufficiencyDiseaseId: Optional[str] = None


class Domino(BaseModel):
    geneSymbol: Optional[str] = None
    score: Optional[float] = None


class DecipherHi(BaseModel):
    hgncId: Optional[str] = None
    hgncSymbol: Optional[str] = None
    pHi: Optional[float] = None
    hiIndex: Optional[float] = None


class GeneInfo(BaseModel):
    acmgSf: Optional[Any] = None
    clingen: Optional[Clingen] = None
    dbnsfp: Optional[Any] = None
    gnomadConstraints: Optional[Any] = None
    hgnc: Optional[Any] = None
    ncbi: Optional[Any] = None
    omim: Optional[Any] = None
    rcnv: Optional[Any] = None
    shet: Optional[Any] = None
    gtex: Optional[Any] = None
    domino: Optional[Domino] = None
    decipherHi: Optional[DecipherHi] = None
    panelapp: List[Any] = []
    conditions: Optional[Any] = None


class Genes(RootModel):
    root: Dict[str, GeneInfo]


class AnnonarsGeneResponse(BaseModel):
    genes: Genes
