# generated by datamodel-codegen:
#   filename:  ex.json
#   timestamp: 2024-03-20T17:05:32+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Query(BaseModel):
    genome_release: str
    chromosome: str
    start: int
    stop: int


class VepItem(BaseModel):
    allele: Optional[str] = None
    consequence: Optional[str] = None
    impact: Optional[str] = None
    symbol: Optional[str] = None
    gene: Optional[str] = None
    featureType: Optional[str] = None
    feature: Optional[str] = None
    featureBiotype: Optional[str] = None
    intron: Optional[str] = None
    hgvsc: Optional[str] = None
    existingVariation: Optional[str] = None
    dbsnpId: Optional[str] = None
    strand: Optional[str] = None
    variantClass: Optional[str] = None
    minimised: Optional[str] = None
    symbolSource: Optional[str] = None
    hgncId: Optional[str] = None
    canonical: Optional[bool] = None
    ccds: Optional[str] = None
    ensp: Optional[str] = None
    swissprot: Optional[str] = None
    uniparc: Optional[str] = None
    genePheno: Optional[str] = None
    gmaf: Optional[float] = None
    amrMaf: Optional[float] = None
    easMaf: Optional[float] = None
    eurMaf: Optional[float] = None
    sasMaf: Optional[float] = None
    aaMaf: Optional[float] = None
    trembl: Optional[str] = None


class Overall(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    af: Optional[float] = None


class Xx(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    af: Optional[float] = None


class Xy(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    af: Optional[float] = None


class Counts(BaseModel):
    overall: Optional[Overall] = None
    xx: Optional[Xx] = None
    xy: Optional[Xy] = None


class ByPopulationItem(BaseModel):
    population: str
    counts: Counts
    faf95: Optional[float] = None
    faf99: Optional[float] = None


class BySex(BaseModel):
    overall: Optional[Overall] = None
    xx: Optional[Xx] = None
    xy: Optional[Xy] = None


class Raw(BaseModel):
    ac: Optional[int] = None
    an: Optional[int] = None
    af: Optional[float] = None


class AlleleCount(BaseModel):
    byPopulation: List[ByPopulationItem]
    bySex: BySex
    raw: Optional[Raw] = None
    popmax: Optional[str] = None
    afPopmax: Optional[float] = None
    acPopmax: Optional[int] = None
    anPopmax: Optional[int] = None
    nhomaltPopmax: Optional[int] = None
    cohort: Optional[str] = None


class VariantInfo(BaseModel):
    variantType: str
    alleleType: str
    nAltAlleles: int


class QualityInfo(BaseModel):
    fs: float
    inbreedingCoeff: float
    mq: float
    mqRankSum: float
    qd: float
    readPosRankSum: float
    vqsrPositiveTrainSite: Optional[bool] = None
    baseQRankSum: float
    clippingRankSum: float
    sor: float
    dp: int
    vqslod: float
    vqsrCulprit: str
    pabMax: float


class ReferenceAssertion(BaseModel):
    rcv: Optional[str] = None
    title: Optional[str] = None
    clinicalSignificance: Optional[str] = None
    reviewStatus: Optional[str] = None


class ClinvarItem(BaseModel):
    release: Optional[str] = None
    chromosome: Optional[str] = None
    start: Optional[int] = None
    stop: Optional[int] = None
    reference: Optional[str] = None
    alternative: Optional[str] = None
    vcv: Optional[str] = None
    referenceAssertions: Optional[List[ReferenceAssertion]] = None


class GnomadGenome(BaseModel):
    chrom: Optional[str] = None
    pos: Optional[int] = None
    refAllele: Optional[str] = None
    altAllele: Optional[str] = None
    vep: Optional[List[VepItem]] = None
    alleleCounts: Optional[List[AlleleCount]] = None
    variantInfo: Optional[Any] = None
    qualityInfo: Optional[Any] = None
    ageInfo: Optional[Any] = None


class AnnonarsRangeResult(BaseModel):
    cadd: Optional[Any] = None
    dbsnp: Optional[List[Any]] = None
    dbnsfp: Optional[Dict[str, Any]] = None
    dbscsnv: Optional[Dict[str, Any]] = None
    gnomad_mtdna: Optional[Any] = None
    gnomad_exomes: Optional[Any] = None
    gnomad_genomes: Optional[List[GnomadGenome]] = None
    helixmtdb: Optional[Any] = None
    ucsc_conservation: Optional[Any] = None
    clinvar: Optional[List[ClinvarItem]] = None


class AnnonarsRangeResponse(BaseModel):
    server_version: str
    query: Query
    result: AnnonarsRangeResult
