# generated by datamodel-codegen:
#   filename:  mehari_gene.json
#   timestamp: 2024-03-20T15:07:23+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel

# ====================
# Mehari Gene
# ====================


class Exon(BaseModel):
    altStartI: int
    altEndI: int
    altCdsStartI: int
    altCdsEndI: int
    cigar: str
    ord: Optional[int] = None


class GenomeAlignment(BaseModel):
    genomeBuild: str
    contig: str
    cdsStart: int
    cdsEnd: int
    strand: str
    exons: List[Exon]


class TranscriptGene(BaseModel):
    id: str
    geneSymbol: str
    geneId: str
    biotype: str
    protein: str
    startCodon: int
    stopCodon: int
    genomeAlignments: List[GenomeAlignment]
    tags: Optional[List[str]] = None


class GeneTranscripts(BaseModel):
    transcripts: List[TranscriptGene]


# ====================
# Mehari Seqvar
# ====================


class Version(BaseModel):
    tx_db: str
    mehari: str


class Query(BaseModel):
    genome_release: str
    chromosome: str
    position: int
    reference: str
    alternative: str
    hgnc_id: Optional[str] = None


class SoTerm(BaseModel):
    term: str


class FeatureType(BaseModel):
    SoTerm: SoTerm


class Rank(BaseModel):
    ord: int
    total: int


class TxPos(BaseModel):
    ord: int
    total: int


class CdsPos(BaseModel):
    ord: int
    total: int


class ProteinPos(BaseModel):
    ord: int
    total: int


class TranscriptSeqvar(BaseModel):
    consequences: List[str]
    putative_impact: str
    gene_symbol: str
    gene_id: str
    feature_type: FeatureType
    feature_id: str
    feature_biotype: str
    feature_tag: List[str]
    rank: Optional[Union[str, Rank]] = None
    hgvs_t: Optional[str] = None
    hgvs_p: Optional[str] = None
    tx_pos: Optional[Union[str, TxPos]] = None
    cds_pos: Optional[Union[str, CdsPos]] = None
    protein_pos: Optional[Union[str, ProteinPos]] = None
    distance: int
    messages: Optional[str] = None


class TranscriptsSeqVar(BaseModel):
    version: Version
    query: Query
    result: List[TranscriptSeqvar]
