# generated by datamodel-codegen:
#   filename:  mehari_gene.json
#   timestamp: 2024-03-20T15:07:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Exon(BaseModel):
    altStartI: int
    altEndI: int
    altCdsStartI: int
    altCdsEndI: int
    cigar: str
    ord: Optional[int] = None


class GenomeAlignment(BaseModel):
    genomeBuild: str
    contig: str
    cdsStart: int
    cdsEnd: int
    strand: str
    exons: List[Exon]


class TranscriptGene(BaseModel):
    id: str
    geneSymbol: str
    geneId: str
    biotype: str
    protein: str
    startCodon: int
    stopCodon: int
    genomeAlignments: List[GenomeAlignment]
    tags: Optional[List[str]] = None


class GeneTranscripts(BaseModel):
    transcripts: List[TranscriptGene]
