name: CI

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         lfs: 'true'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Lint source code
        run: make lint

  Unit-Test:
    runs-on: ubuntu-latest
    needs:
      - Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         lfs: 'true'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make ci-unit-test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: main
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: bihealth/auto-acmg

  End2End-Test:
    runs-on: ubuntu-latest
    needs:
      - Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         lfs: 'true'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make ci-e2e-test

  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         lfs: 'true'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install docs dependencies
        run: make ci-docs-deps

      - name: Build documentation
        run: make ci-docs


